// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Table is the predicate function for table builders.
type Table func(*sql.Selector)

// TableCategory is the predicate function for tablecategory builders.
type TableCategory func(*sql.Selector)
