// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/solikewind/happyeat/dal/model/ent/categoryspec"
	"github.com/solikewind/happyeat/dal/model/ent/menucategory"
)

// 菜单分类的规格模板
type CategorySpec struct {
	config `json:"-"`
	// ID of the ent.
	// ID
	ID uint64 `json:"id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 删除时间戳
	DeleteTs int64 `json:"delete_ts,omitempty"`
	// 菜单分类ID
	MenuCategoryID uint64 `json:"menu_category_id,omitempty"`
	// 规格类型，如辣度、容量
	SpecType string `json:"spec_type,omitempty"`
	// 规格选项，如微辣、大杯
	SpecValue string `json:"spec_value,omitempty"`
	// 加价
	PriceDelta int64 `json:"price_delta,omitempty"`
	// 排序
	Sort uint32 `json:"sort,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CategorySpecQuery when eager-loading is set.
	Edges        CategorySpecEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CategorySpecEdges holds the relations/edges for other nodes in the graph.
type CategorySpecEdges struct {
	// Category holds the value of the category edge.
	Category *MenuCategory `json:"category,omitempty"`
	// MenuSpecs holds the value of the menu_specs edge.
	MenuSpecs []*MenuSpec `json:"menu_specs,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// CategoryOrErr returns the Category value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CategorySpecEdges) CategoryOrErr() (*MenuCategory, error) {
	if e.Category != nil {
		return e.Category, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: menucategory.Label}
	}
	return nil, &NotLoadedError{edge: "category"}
}

// MenuSpecsOrErr returns the MenuSpecs value or an error if the edge
// was not loaded in eager-loading.
func (e CategorySpecEdges) MenuSpecsOrErr() ([]*MenuSpec, error) {
	if e.loadedTypes[1] {
		return e.MenuSpecs, nil
	}
	return nil, &NotLoadedError{edge: "menu_specs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CategorySpec) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case categoryspec.FieldID, categoryspec.FieldDeleteTs, categoryspec.FieldMenuCategoryID, categoryspec.FieldPriceDelta, categoryspec.FieldSort:
			values[i] = new(sql.NullInt64)
		case categoryspec.FieldSpecType, categoryspec.FieldSpecValue:
			values[i] = new(sql.NullString)
		case categoryspec.FieldCreatedAt, categoryspec.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CategorySpec fields.
func (_m *CategorySpec) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case categoryspec.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case categoryspec.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case categoryspec.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case categoryspec.FieldDeleteTs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field delete_ts", values[i])
			} else if value.Valid {
				_m.DeleteTs = value.Int64
			}
		case categoryspec.FieldMenuCategoryID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field menu_category_id", values[i])
			} else if value.Valid {
				_m.MenuCategoryID = uint64(value.Int64)
			}
		case categoryspec.FieldSpecType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field spec_type", values[i])
			} else if value.Valid {
				_m.SpecType = value.String
			}
		case categoryspec.FieldSpecValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field spec_value", values[i])
			} else if value.Valid {
				_m.SpecValue = value.String
			}
		case categoryspec.FieldPriceDelta:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field price_delta", values[i])
			} else if value.Valid {
				_m.PriceDelta = value.Int64
			}
		case categoryspec.FieldSort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort", values[i])
			} else if value.Valid {
				_m.Sort = uint32(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CategorySpec.
// This includes values selected through modifiers, order, etc.
func (_m *CategorySpec) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCategory queries the "category" edge of the CategorySpec entity.
func (_m *CategorySpec) QueryCategory() *MenuCategoryQuery {
	return NewCategorySpecClient(_m.config).QueryCategory(_m)
}

// QueryMenuSpecs queries the "menu_specs" edge of the CategorySpec entity.
func (_m *CategorySpec) QueryMenuSpecs() *MenuSpecQuery {
	return NewCategorySpecClient(_m.config).QueryMenuSpecs(_m)
}

// Update returns a builder for updating this CategorySpec.
// Note that you need to call CategorySpec.Unwrap() before calling this method if this CategorySpec
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CategorySpec) Update() *CategorySpecUpdateOne {
	return NewCategorySpecClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CategorySpec entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CategorySpec) Unwrap() *CategorySpec {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CategorySpec is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CategorySpec) String() string {
	var builder strings.Builder
	builder.WriteString("CategorySpec(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("delete_ts=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeleteTs))
	builder.WriteString(", ")
	builder.WriteString("menu_category_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.MenuCategoryID))
	builder.WriteString(", ")
	builder.WriteString("spec_type=")
	builder.WriteString(_m.SpecType)
	builder.WriteString(", ")
	builder.WriteString("spec_value=")
	builder.WriteString(_m.SpecValue)
	builder.WriteString(", ")
	builder.WriteString("price_delta=")
	builder.WriteString(fmt.Sprintf("%v", _m.PriceDelta))
	builder.WriteString(", ")
	builder.WriteString("sort=")
	builder.WriteString(fmt.Sprintf("%v", _m.Sort))
	builder.WriteByte(')')
	return builder.String()
}

// CategorySpecs is a parsable slice of CategorySpec.
type CategorySpecs []*CategorySpec
