// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/solikewind/happyeat/dal/model/ent/categoryspec"
	"github.com/solikewind/happyeat/dal/model/ent/menucategory"
	"github.com/solikewind/happyeat/dal/model/ent/menuspec"
	"github.com/solikewind/happyeat/dal/model/ent/predicate"
	"github.com/solikewind/happyeat/dal/model/ent/specitem"
)

// CategorySpecQuery is the builder for querying CategorySpec entities.
type CategorySpecQuery struct {
	config
	ctx           *QueryContext
	order         []categoryspec.OrderOption
	inters        []Interceptor
	predicates    []predicate.CategorySpec
	withCategory  *MenuCategoryQuery
	withSpecItem  *SpecItemQuery
	withMenuSpecs *MenuSpecQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CategorySpecQuery builder.
func (_q *CategorySpecQuery) Where(ps ...predicate.CategorySpec) *CategorySpecQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *CategorySpecQuery) Limit(limit int) *CategorySpecQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *CategorySpecQuery) Offset(offset int) *CategorySpecQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *CategorySpecQuery) Unique(unique bool) *CategorySpecQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *CategorySpecQuery) Order(o ...categoryspec.OrderOption) *CategorySpecQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryCategory chains the current query on the "category" edge.
func (_q *CategorySpecQuery) QueryCategory() *MenuCategoryQuery {
	query := (&MenuCategoryClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(categoryspec.Table, categoryspec.FieldID, selector),
			sqlgraph.To(menucategory.Table, menucategory.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, categoryspec.CategoryTable, categoryspec.CategoryColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySpecItem chains the current query on the "spec_item" edge.
func (_q *CategorySpecQuery) QuerySpecItem() *SpecItemQuery {
	query := (&SpecItemClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(categoryspec.Table, categoryspec.FieldID, selector),
			sqlgraph.To(specitem.Table, specitem.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, categoryspec.SpecItemTable, categoryspec.SpecItemColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMenuSpecs chains the current query on the "menu_specs" edge.
func (_q *CategorySpecQuery) QueryMenuSpecs() *MenuSpecQuery {
	query := (&MenuSpecClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(categoryspec.Table, categoryspec.FieldID, selector),
			sqlgraph.To(menuspec.Table, menuspec.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, categoryspec.MenuSpecsTable, categoryspec.MenuSpecsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CategorySpec entity from the query.
// Returns a *NotFoundError when no CategorySpec was found.
func (_q *CategorySpecQuery) First(ctx context.Context) (*CategorySpec, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{categoryspec.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *CategorySpecQuery) FirstX(ctx context.Context) *CategorySpec {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CategorySpec ID from the query.
// Returns a *NotFoundError when no CategorySpec ID was found.
func (_q *CategorySpecQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{categoryspec.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *CategorySpecQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CategorySpec entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CategorySpec entity is found.
// Returns a *NotFoundError when no CategorySpec entities are found.
func (_q *CategorySpecQuery) Only(ctx context.Context) (*CategorySpec, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{categoryspec.Label}
	default:
		return nil, &NotSingularError{categoryspec.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *CategorySpecQuery) OnlyX(ctx context.Context) *CategorySpec {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CategorySpec ID in the query.
// Returns a *NotSingularError when more than one CategorySpec ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *CategorySpecQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{categoryspec.Label}
	default:
		err = &NotSingularError{categoryspec.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *CategorySpecQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CategorySpecs.
func (_q *CategorySpecQuery) All(ctx context.Context) ([]*CategorySpec, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CategorySpec, *CategorySpecQuery]()
	return withInterceptors[[]*CategorySpec](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *CategorySpecQuery) AllX(ctx context.Context) []*CategorySpec {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CategorySpec IDs.
func (_q *CategorySpecQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(categoryspec.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *CategorySpecQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *CategorySpecQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*CategorySpecQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *CategorySpecQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *CategorySpecQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *CategorySpecQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CategorySpecQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *CategorySpecQuery) Clone() *CategorySpecQuery {
	if _q == nil {
		return nil
	}
	return &CategorySpecQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]categoryspec.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.CategorySpec{}, _q.predicates...),
		withCategory:  _q.withCategory.Clone(),
		withSpecItem:  _q.withSpecItem.Clone(),
		withMenuSpecs: _q.withMenuSpecs.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithCategory tells the query-builder to eager-load the nodes that are connected to
// the "category" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CategorySpecQuery) WithCategory(opts ...func(*MenuCategoryQuery)) *CategorySpecQuery {
	query := (&MenuCategoryClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCategory = query
	return _q
}

// WithSpecItem tells the query-builder to eager-load the nodes that are connected to
// the "spec_item" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CategorySpecQuery) WithSpecItem(opts ...func(*SpecItemQuery)) *CategorySpecQuery {
	query := (&SpecItemClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSpecItem = query
	return _q
}

// WithMenuSpecs tells the query-builder to eager-load the nodes that are connected to
// the "menu_specs" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CategorySpecQuery) WithMenuSpecs(opts ...func(*MenuSpecQuery)) *CategorySpecQuery {
	query := (&MenuSpecClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMenuSpecs = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CategorySpec.Query().
//		GroupBy(categoryspec.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *CategorySpecQuery) GroupBy(field string, fields ...string) *CategorySpecGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CategorySpecGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = categoryspec.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.CategorySpec.Query().
//		Select(categoryspec.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *CategorySpecQuery) Select(fields ...string) *CategorySpecSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &CategorySpecSelect{CategorySpecQuery: _q}
	sbuild.label = categoryspec.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CategorySpecSelect configured with the given aggregations.
func (_q *CategorySpecQuery) Aggregate(fns ...AggregateFunc) *CategorySpecSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *CategorySpecQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !categoryspec.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *CategorySpecQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CategorySpec, error) {
	var (
		nodes       = []*CategorySpec{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withCategory != nil,
			_q.withSpecItem != nil,
			_q.withMenuSpecs != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CategorySpec).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CategorySpec{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withCategory; query != nil {
		if err := _q.loadCategory(ctx, query, nodes, nil,
			func(n *CategorySpec, e *MenuCategory) { n.Edges.Category = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSpecItem; query != nil {
		if err := _q.loadSpecItem(ctx, query, nodes, nil,
			func(n *CategorySpec, e *SpecItem) { n.Edges.SpecItem = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withMenuSpecs; query != nil {
		if err := _q.loadMenuSpecs(ctx, query, nodes,
			func(n *CategorySpec) { n.Edges.MenuSpecs = []*MenuSpec{} },
			func(n *CategorySpec, e *MenuSpec) { n.Edges.MenuSpecs = append(n.Edges.MenuSpecs, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *CategorySpecQuery) loadCategory(ctx context.Context, query *MenuCategoryQuery, nodes []*CategorySpec, init func(*CategorySpec), assign func(*CategorySpec, *MenuCategory)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*CategorySpec)
	for i := range nodes {
		fk := nodes[i].MenuCategoryID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(menucategory.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "menu_category_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *CategorySpecQuery) loadSpecItem(ctx context.Context, query *SpecItemQuery, nodes []*CategorySpec, init func(*CategorySpec), assign func(*CategorySpec, *SpecItem)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*CategorySpec)
	for i := range nodes {
		if nodes[i].SpecItemID == nil {
			continue
		}
		fk := *nodes[i].SpecItemID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(specitem.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "spec_item_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *CategorySpecQuery) loadMenuSpecs(ctx context.Context, query *MenuSpecQuery, nodes []*CategorySpec, init func(*CategorySpec), assign func(*CategorySpec, *MenuSpec)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uint64]*CategorySpec)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(menuspec.FieldCategorySpecID)
	}
	query.Where(predicate.MenuSpec(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(categoryspec.MenuSpecsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CategorySpecID
		if fk == nil {
			return fmt.Errorf(`foreign-key "category_spec_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "category_spec_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *CategorySpecQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *CategorySpecQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(categoryspec.Table, categoryspec.Columns, sqlgraph.NewFieldSpec(categoryspec.FieldID, field.TypeUint64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, categoryspec.FieldID)
		for i := range fields {
			if fields[i] != categoryspec.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withCategory != nil {
			_spec.Node.AddColumnOnce(categoryspec.FieldMenuCategoryID)
		}
		if _q.withSpecItem != nil {
			_spec.Node.AddColumnOnce(categoryspec.FieldSpecItemID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *CategorySpecQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(categoryspec.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = categoryspec.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CategorySpecGroupBy is the group-by builder for CategorySpec entities.
type CategorySpecGroupBy struct {
	selector
	build *CategorySpecQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *CategorySpecGroupBy) Aggregate(fns ...AggregateFunc) *CategorySpecGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *CategorySpecGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CategorySpecQuery, *CategorySpecGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *CategorySpecGroupBy) sqlScan(ctx context.Context, root *CategorySpecQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CategorySpecSelect is the builder for selecting fields of CategorySpec entities.
type CategorySpecSelect struct {
	*CategorySpecQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *CategorySpecSelect) Aggregate(fns ...AggregateFunc) *CategorySpecSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *CategorySpecSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CategorySpecQuery, *CategorySpecSelect](ctx, _s.CategorySpecQuery, _s, _s.inters, v)
}

func (_s *CategorySpecSelect) sqlScan(ctx context.Context, root *CategorySpecQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
