// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/solikewind/happyeat/dal/model/ent/iampermission"
	"github.com/solikewind/happyeat/dal/model/ent/predicate"
)

// IAMPermissionDelete is the builder for deleting a IAMPermission entity.
type IAMPermissionDelete struct {
	config
	hooks    []Hook
	mutation *IAMPermissionMutation
}

// Where appends a list predicates to the IAMPermissionDelete builder.
func (_d *IAMPermissionDelete) Where(ps ...predicate.IAMPermission) *IAMPermissionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *IAMPermissionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *IAMPermissionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *IAMPermissionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(iampermission.Table, sqlgraph.NewFieldSpec(iampermission.FieldID, field.TypeUint64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// IAMPermissionDeleteOne is the builder for deleting a single IAMPermission entity.
type IAMPermissionDeleteOne struct {
	_d *IAMPermissionDelete
}

// Where appends a list predicates to the IAMPermissionDelete builder.
func (_d *IAMPermissionDeleteOne) Where(ps ...predicate.IAMPermission) *IAMPermissionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *IAMPermissionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{iampermission.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *IAMPermissionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
