// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/solikewind/happyeat/dal/model/ent/iamuser"
)

// RBAC 用户主体
type IAMUser struct {
	config `json:"-"`
	// ID of the ent.
	// ID
	ID uint64 `json:"id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 删除时间戳
	DeleteTs int64 `json:"delete_ts,omitempty"`
	// 用户编码
	UserCode string `json:"user_code,omitempty"`
	// 展示名
	DisplayName string `json:"display_name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the IAMUserQuery when eager-loading is set.
	Edges        IAMUserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// IAMUserEdges holds the relations/edges for other nodes in the graph.
type IAMUserEdges struct {
	// Roles holds the value of the roles edge.
	Roles []*IAMRole `json:"roles,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RolesOrErr returns the Roles value or an error if the edge
// was not loaded in eager-loading.
func (e IAMUserEdges) RolesOrErr() ([]*IAMRole, error) {
	if e.loadedTypes[0] {
		return e.Roles, nil
	}
	return nil, &NotLoadedError{edge: "roles"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IAMUser) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case iamuser.FieldID, iamuser.FieldDeleteTs:
			values[i] = new(sql.NullInt64)
		case iamuser.FieldUserCode, iamuser.FieldDisplayName:
			values[i] = new(sql.NullString)
		case iamuser.FieldCreatedAt, iamuser.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IAMUser fields.
func (_m *IAMUser) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case iamuser.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case iamuser.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case iamuser.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case iamuser.FieldDeleteTs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field delete_ts", values[i])
			} else if value.Valid {
				_m.DeleteTs = value.Int64
			}
		case iamuser.FieldUserCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_code", values[i])
			} else if value.Valid {
				_m.UserCode = value.String
			}
		case iamuser.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the IAMUser.
// This includes values selected through modifiers, order, etc.
func (_m *IAMUser) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRoles queries the "roles" edge of the IAMUser entity.
func (_m *IAMUser) QueryRoles() *IAMRoleQuery {
	return NewIAMUserClient(_m.config).QueryRoles(_m)
}

// Update returns a builder for updating this IAMUser.
// Note that you need to call IAMUser.Unwrap() before calling this method if this IAMUser
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *IAMUser) Update() *IAMUserUpdateOne {
	return NewIAMUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the IAMUser entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *IAMUser) Unwrap() *IAMUser {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: IAMUser is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *IAMUser) String() string {
	var builder strings.Builder
	builder.WriteString("IAMUser(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("delete_ts=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeleteTs))
	builder.WriteString(", ")
	builder.WriteString("user_code=")
	builder.WriteString(_m.UserCode)
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(_m.DisplayName)
	builder.WriteByte(')')
	return builder.String()
}

// IAMUsers is a parsable slice of IAMUser.
type IAMUsers []*IAMUser
