// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/solikewind/happyeat/dal/model/ent/menu"
	"github.com/solikewind/happyeat/dal/model/ent/menuspec"
)

// MenuSpecCreate is the builder for creating a MenuSpec entity.
type MenuSpecCreate struct {
	config
	mutation *MenuSpecMutation
	hooks    []Hook
}

// SetSpecType sets the "spec_type" field.
func (_c *MenuSpecCreate) SetSpecType(v string) *MenuSpecCreate {
	_c.mutation.SetSpecType(v)
	return _c
}

// SetSpecValue sets the "spec_value" field.
func (_c *MenuSpecCreate) SetSpecValue(v string) *MenuSpecCreate {
	_c.mutation.SetSpecValue(v)
	return _c
}

// SetPriceDelta sets the "price_delta" field.
func (_c *MenuSpecCreate) SetPriceDelta(v float64) *MenuSpecCreate {
	_c.mutation.SetPriceDelta(v)
	return _c
}

// SetNillablePriceDelta sets the "price_delta" field if the given value is not nil.
func (_c *MenuSpecCreate) SetNillablePriceDelta(v *float64) *MenuSpecCreate {
	if v != nil {
		_c.SetPriceDelta(*v)
	}
	return _c
}

// SetSort sets the "sort" field.
func (_c *MenuSpecCreate) SetSort(v int) *MenuSpecCreate {
	_c.mutation.SetSort(v)
	return _c
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_c *MenuSpecCreate) SetNillableSort(v *int) *MenuSpecCreate {
	if v != nil {
		_c.SetSort(*v)
	}
	return _c
}

// SetMenuID sets the "menu" edge to the Menu entity by ID.
func (_c *MenuSpecCreate) SetMenuID(id int) *MenuSpecCreate {
	_c.mutation.SetMenuID(id)
	return _c
}

// SetMenu sets the "menu" edge to the Menu entity.
func (_c *MenuSpecCreate) SetMenu(v *Menu) *MenuSpecCreate {
	return _c.SetMenuID(v.ID)
}

// Mutation returns the MenuSpecMutation object of the builder.
func (_c *MenuSpecCreate) Mutation() *MenuSpecMutation {
	return _c.mutation
}

// Save creates the MenuSpec in the database.
func (_c *MenuSpecCreate) Save(ctx context.Context) (*MenuSpec, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MenuSpecCreate) SaveX(ctx context.Context) *MenuSpec {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MenuSpecCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MenuSpecCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MenuSpecCreate) defaults() {
	if _, ok := _c.mutation.PriceDelta(); !ok {
		v := menuspec.DefaultPriceDelta
		_c.mutation.SetPriceDelta(v)
	}
	if _, ok := _c.mutation.Sort(); !ok {
		v := menuspec.DefaultSort
		_c.mutation.SetSort(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MenuSpecCreate) check() error {
	if _, ok := _c.mutation.SpecType(); !ok {
		return &ValidationError{Name: "spec_type", err: errors.New(`ent: missing required field "MenuSpec.spec_type"`)}
	}
	if v, ok := _c.mutation.SpecType(); ok {
		if err := menuspec.SpecTypeValidator(v); err != nil {
			return &ValidationError{Name: "spec_type", err: fmt.Errorf(`ent: validator failed for field "MenuSpec.spec_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SpecValue(); !ok {
		return &ValidationError{Name: "spec_value", err: errors.New(`ent: missing required field "MenuSpec.spec_value"`)}
	}
	if v, ok := _c.mutation.SpecValue(); ok {
		if err := menuspec.SpecValueValidator(v); err != nil {
			return &ValidationError{Name: "spec_value", err: fmt.Errorf(`ent: validator failed for field "MenuSpec.spec_value": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PriceDelta(); !ok {
		return &ValidationError{Name: "price_delta", err: errors.New(`ent: missing required field "MenuSpec.price_delta"`)}
	}
	if _, ok := _c.mutation.Sort(); !ok {
		return &ValidationError{Name: "sort", err: errors.New(`ent: missing required field "MenuSpec.sort"`)}
	}
	if len(_c.mutation.MenuIDs()) == 0 {
		return &ValidationError{Name: "menu", err: errors.New(`ent: missing required edge "MenuSpec.menu"`)}
	}
	return nil
}

func (_c *MenuSpecCreate) sqlSave(ctx context.Context) (*MenuSpec, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MenuSpecCreate) createSpec() (*MenuSpec, *sqlgraph.CreateSpec) {
	var (
		_node = &MenuSpec{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(menuspec.Table, sqlgraph.NewFieldSpec(menuspec.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.SpecType(); ok {
		_spec.SetField(menuspec.FieldSpecType, field.TypeString, value)
		_node.SpecType = value
	}
	if value, ok := _c.mutation.SpecValue(); ok {
		_spec.SetField(menuspec.FieldSpecValue, field.TypeString, value)
		_node.SpecValue = value
	}
	if value, ok := _c.mutation.PriceDelta(); ok {
		_spec.SetField(menuspec.FieldPriceDelta, field.TypeFloat64, value)
		_node.PriceDelta = value
	}
	if value, ok := _c.mutation.Sort(); ok {
		_spec.SetField(menuspec.FieldSort, field.TypeInt, value)
		_node.Sort = value
	}
	if nodes := _c.mutation.MenuIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   menuspec.MenuTable,
			Columns: []string{menuspec.MenuColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menu.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.menu_specs = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MenuSpecCreateBulk is the builder for creating many MenuSpec entities in bulk.
type MenuSpecCreateBulk struct {
	config
	err      error
	builders []*MenuSpecCreate
}

// Save creates the MenuSpec entities in the database.
func (_c *MenuSpecCreateBulk) Save(ctx context.Context) ([]*MenuSpec, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MenuSpec, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MenuSpecMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MenuSpecCreateBulk) SaveX(ctx context.Context) []*MenuSpec {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MenuSpecCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MenuSpecCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
