// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/solikewind/happyeat/dal/model/ent/menu"
	"github.com/solikewind/happyeat/dal/model/ent/menuspec"
	"github.com/solikewind/happyeat/dal/model/ent/predicate"
)

// MenuSpecUpdate is the builder for updating MenuSpec entities.
type MenuSpecUpdate struct {
	config
	hooks    []Hook
	mutation *MenuSpecMutation
}

// Where appends a list predicates to the MenuSpecUpdate builder.
func (_u *MenuSpecUpdate) Where(ps ...predicate.MenuSpec) *MenuSpecUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSpecType sets the "spec_type" field.
func (_u *MenuSpecUpdate) SetSpecType(v string) *MenuSpecUpdate {
	_u.mutation.SetSpecType(v)
	return _u
}

// SetNillableSpecType sets the "spec_type" field if the given value is not nil.
func (_u *MenuSpecUpdate) SetNillableSpecType(v *string) *MenuSpecUpdate {
	if v != nil {
		_u.SetSpecType(*v)
	}
	return _u
}

// SetSpecValue sets the "spec_value" field.
func (_u *MenuSpecUpdate) SetSpecValue(v string) *MenuSpecUpdate {
	_u.mutation.SetSpecValue(v)
	return _u
}

// SetNillableSpecValue sets the "spec_value" field if the given value is not nil.
func (_u *MenuSpecUpdate) SetNillableSpecValue(v *string) *MenuSpecUpdate {
	if v != nil {
		_u.SetSpecValue(*v)
	}
	return _u
}

// SetPriceDelta sets the "price_delta" field.
func (_u *MenuSpecUpdate) SetPriceDelta(v float64) *MenuSpecUpdate {
	_u.mutation.ResetPriceDelta()
	_u.mutation.SetPriceDelta(v)
	return _u
}

// SetNillablePriceDelta sets the "price_delta" field if the given value is not nil.
func (_u *MenuSpecUpdate) SetNillablePriceDelta(v *float64) *MenuSpecUpdate {
	if v != nil {
		_u.SetPriceDelta(*v)
	}
	return _u
}

// AddPriceDelta adds value to the "price_delta" field.
func (_u *MenuSpecUpdate) AddPriceDelta(v float64) *MenuSpecUpdate {
	_u.mutation.AddPriceDelta(v)
	return _u
}

// SetSort sets the "sort" field.
func (_u *MenuSpecUpdate) SetSort(v int) *MenuSpecUpdate {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *MenuSpecUpdate) SetNillableSort(v *int) *MenuSpecUpdate {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *MenuSpecUpdate) AddSort(v int) *MenuSpecUpdate {
	_u.mutation.AddSort(v)
	return _u
}

// SetMenuID sets the "menu" edge to the Menu entity by ID.
func (_u *MenuSpecUpdate) SetMenuID(id int) *MenuSpecUpdate {
	_u.mutation.SetMenuID(id)
	return _u
}

// SetMenu sets the "menu" edge to the Menu entity.
func (_u *MenuSpecUpdate) SetMenu(v *Menu) *MenuSpecUpdate {
	return _u.SetMenuID(v.ID)
}

// Mutation returns the MenuSpecMutation object of the builder.
func (_u *MenuSpecUpdate) Mutation() *MenuSpecMutation {
	return _u.mutation
}

// ClearMenu clears the "menu" edge to the Menu entity.
func (_u *MenuSpecUpdate) ClearMenu() *MenuSpecUpdate {
	_u.mutation.ClearMenu()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MenuSpecUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MenuSpecUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MenuSpecUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MenuSpecUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MenuSpecUpdate) check() error {
	if v, ok := _u.mutation.SpecType(); ok {
		if err := menuspec.SpecTypeValidator(v); err != nil {
			return &ValidationError{Name: "spec_type", err: fmt.Errorf(`ent: validator failed for field "MenuSpec.spec_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SpecValue(); ok {
		if err := menuspec.SpecValueValidator(v); err != nil {
			return &ValidationError{Name: "spec_value", err: fmt.Errorf(`ent: validator failed for field "MenuSpec.spec_value": %w`, err)}
		}
	}
	if _u.mutation.MenuCleared() && len(_u.mutation.MenuIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MenuSpec.menu"`)
	}
	return nil
}

func (_u *MenuSpecUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(menuspec.Table, menuspec.Columns, sqlgraph.NewFieldSpec(menuspec.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SpecType(); ok {
		_spec.SetField(menuspec.FieldSpecType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SpecValue(); ok {
		_spec.SetField(menuspec.FieldSpecValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.PriceDelta(); ok {
		_spec.SetField(menuspec.FieldPriceDelta, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPriceDelta(); ok {
		_spec.AddField(menuspec.FieldPriceDelta, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(menuspec.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(menuspec.FieldSort, field.TypeInt, value)
	}
	if _u.mutation.MenuCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   menuspec.MenuTable,
			Columns: []string{menuspec.MenuColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menu.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MenuIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   menuspec.MenuTable,
			Columns: []string{menuspec.MenuColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menu.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{menuspec.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MenuSpecUpdateOne is the builder for updating a single MenuSpec entity.
type MenuSpecUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MenuSpecMutation
}

// SetSpecType sets the "spec_type" field.
func (_u *MenuSpecUpdateOne) SetSpecType(v string) *MenuSpecUpdateOne {
	_u.mutation.SetSpecType(v)
	return _u
}

// SetNillableSpecType sets the "spec_type" field if the given value is not nil.
func (_u *MenuSpecUpdateOne) SetNillableSpecType(v *string) *MenuSpecUpdateOne {
	if v != nil {
		_u.SetSpecType(*v)
	}
	return _u
}

// SetSpecValue sets the "spec_value" field.
func (_u *MenuSpecUpdateOne) SetSpecValue(v string) *MenuSpecUpdateOne {
	_u.mutation.SetSpecValue(v)
	return _u
}

// SetNillableSpecValue sets the "spec_value" field if the given value is not nil.
func (_u *MenuSpecUpdateOne) SetNillableSpecValue(v *string) *MenuSpecUpdateOne {
	if v != nil {
		_u.SetSpecValue(*v)
	}
	return _u
}

// SetPriceDelta sets the "price_delta" field.
func (_u *MenuSpecUpdateOne) SetPriceDelta(v float64) *MenuSpecUpdateOne {
	_u.mutation.ResetPriceDelta()
	_u.mutation.SetPriceDelta(v)
	return _u
}

// SetNillablePriceDelta sets the "price_delta" field if the given value is not nil.
func (_u *MenuSpecUpdateOne) SetNillablePriceDelta(v *float64) *MenuSpecUpdateOne {
	if v != nil {
		_u.SetPriceDelta(*v)
	}
	return _u
}

// AddPriceDelta adds value to the "price_delta" field.
func (_u *MenuSpecUpdateOne) AddPriceDelta(v float64) *MenuSpecUpdateOne {
	_u.mutation.AddPriceDelta(v)
	return _u
}

// SetSort sets the "sort" field.
func (_u *MenuSpecUpdateOne) SetSort(v int) *MenuSpecUpdateOne {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *MenuSpecUpdateOne) SetNillableSort(v *int) *MenuSpecUpdateOne {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *MenuSpecUpdateOne) AddSort(v int) *MenuSpecUpdateOne {
	_u.mutation.AddSort(v)
	return _u
}

// SetMenuID sets the "menu" edge to the Menu entity by ID.
func (_u *MenuSpecUpdateOne) SetMenuID(id int) *MenuSpecUpdateOne {
	_u.mutation.SetMenuID(id)
	return _u
}

// SetMenu sets the "menu" edge to the Menu entity.
func (_u *MenuSpecUpdateOne) SetMenu(v *Menu) *MenuSpecUpdateOne {
	return _u.SetMenuID(v.ID)
}

// Mutation returns the MenuSpecMutation object of the builder.
func (_u *MenuSpecUpdateOne) Mutation() *MenuSpecMutation {
	return _u.mutation
}

// ClearMenu clears the "menu" edge to the Menu entity.
func (_u *MenuSpecUpdateOne) ClearMenu() *MenuSpecUpdateOne {
	_u.mutation.ClearMenu()
	return _u
}

// Where appends a list predicates to the MenuSpecUpdate builder.
func (_u *MenuSpecUpdateOne) Where(ps ...predicate.MenuSpec) *MenuSpecUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MenuSpecUpdateOne) Select(field string, fields ...string) *MenuSpecUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MenuSpec entity.
func (_u *MenuSpecUpdateOne) Save(ctx context.Context) (*MenuSpec, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MenuSpecUpdateOne) SaveX(ctx context.Context) *MenuSpec {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MenuSpecUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MenuSpecUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MenuSpecUpdateOne) check() error {
	if v, ok := _u.mutation.SpecType(); ok {
		if err := menuspec.SpecTypeValidator(v); err != nil {
			return &ValidationError{Name: "spec_type", err: fmt.Errorf(`ent: validator failed for field "MenuSpec.spec_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SpecValue(); ok {
		if err := menuspec.SpecValueValidator(v); err != nil {
			return &ValidationError{Name: "spec_value", err: fmt.Errorf(`ent: validator failed for field "MenuSpec.spec_value": %w`, err)}
		}
	}
	if _u.mutation.MenuCleared() && len(_u.mutation.MenuIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MenuSpec.menu"`)
	}
	return nil
}

func (_u *MenuSpecUpdateOne) sqlSave(ctx context.Context) (_node *MenuSpec, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(menuspec.Table, menuspec.Columns, sqlgraph.NewFieldSpec(menuspec.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MenuSpec.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, menuspec.FieldID)
		for _, f := range fields {
			if !menuspec.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != menuspec.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SpecType(); ok {
		_spec.SetField(menuspec.FieldSpecType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SpecValue(); ok {
		_spec.SetField(menuspec.FieldSpecValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.PriceDelta(); ok {
		_spec.SetField(menuspec.FieldPriceDelta, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPriceDelta(); ok {
		_spec.AddField(menuspec.FieldPriceDelta, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(menuspec.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(menuspec.FieldSort, field.TypeInt, value)
	}
	if _u.mutation.MenuCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   menuspec.MenuTable,
			Columns: []string{menuspec.MenuColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menu.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MenuIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   menuspec.MenuTable,
			Columns: []string{menuspec.MenuColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menu.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MenuSpec{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{menuspec.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
