// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/solikewind/happyeat/dal/model/ent/categoryspec"
	"github.com/solikewind/happyeat/dal/model/ent/menu"
	"github.com/solikewind/happyeat/dal/model/ent/menucategory"
	"github.com/solikewind/happyeat/dal/model/ent/predicate"
)

// MenuCategoryUpdate is the builder for updating MenuCategory entities.
type MenuCategoryUpdate struct {
	config
	hooks    []Hook
	mutation *MenuCategoryMutation
}

// Where appends a list predicates to the MenuCategoryUpdate builder.
func (_u *MenuCategoryUpdate) Where(ps ...predicate.MenuCategory) *MenuCategoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MenuCategoryUpdate) SetUpdatedAt(v time.Time) *MenuCategoryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeleteTs sets the "delete_ts" field.
func (_u *MenuCategoryUpdate) SetDeleteTs(v int64) *MenuCategoryUpdate {
	_u.mutation.ResetDeleteTs()
	_u.mutation.SetDeleteTs(v)
	return _u
}

// SetNillableDeleteTs sets the "delete_ts" field if the given value is not nil.
func (_u *MenuCategoryUpdate) SetNillableDeleteTs(v *int64) *MenuCategoryUpdate {
	if v != nil {
		_u.SetDeleteTs(*v)
	}
	return _u
}

// AddDeleteTs adds value to the "delete_ts" field.
func (_u *MenuCategoryUpdate) AddDeleteTs(v int64) *MenuCategoryUpdate {
	_u.mutation.AddDeleteTs(v)
	return _u
}

// SetName sets the "name" field.
func (_u *MenuCategoryUpdate) SetName(v string) *MenuCategoryUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MenuCategoryUpdate) SetNillableName(v *string) *MenuCategoryUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *MenuCategoryUpdate) SetDescription(v string) *MenuCategoryUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *MenuCategoryUpdate) SetNillableDescription(v *string) *MenuCategoryUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *MenuCategoryUpdate) ClearDescription() *MenuCategoryUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// AddMenuIDs adds the "menus" edge to the Menu entity by IDs.
func (_u *MenuCategoryUpdate) AddMenuIDs(ids ...uint64) *MenuCategoryUpdate {
	_u.mutation.AddMenuIDs(ids...)
	return _u
}

// AddMenus adds the "menus" edges to the Menu entity.
func (_u *MenuCategoryUpdate) AddMenus(v ...*Menu) *MenuCategoryUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMenuIDs(ids...)
}

// AddCategorySpecIDs adds the "category_specs" edge to the CategorySpec entity by IDs.
func (_u *MenuCategoryUpdate) AddCategorySpecIDs(ids ...uint64) *MenuCategoryUpdate {
	_u.mutation.AddCategorySpecIDs(ids...)
	return _u
}

// AddCategorySpecs adds the "category_specs" edges to the CategorySpec entity.
func (_u *MenuCategoryUpdate) AddCategorySpecs(v ...*CategorySpec) *MenuCategoryUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCategorySpecIDs(ids...)
}

// Mutation returns the MenuCategoryMutation object of the builder.
func (_u *MenuCategoryUpdate) Mutation() *MenuCategoryMutation {
	return _u.mutation
}

// ClearMenus clears all "menus" edges to the Menu entity.
func (_u *MenuCategoryUpdate) ClearMenus() *MenuCategoryUpdate {
	_u.mutation.ClearMenus()
	return _u
}

// RemoveMenuIDs removes the "menus" edge to Menu entities by IDs.
func (_u *MenuCategoryUpdate) RemoveMenuIDs(ids ...uint64) *MenuCategoryUpdate {
	_u.mutation.RemoveMenuIDs(ids...)
	return _u
}

// RemoveMenus removes "menus" edges to Menu entities.
func (_u *MenuCategoryUpdate) RemoveMenus(v ...*Menu) *MenuCategoryUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMenuIDs(ids...)
}

// ClearCategorySpecs clears all "category_specs" edges to the CategorySpec entity.
func (_u *MenuCategoryUpdate) ClearCategorySpecs() *MenuCategoryUpdate {
	_u.mutation.ClearCategorySpecs()
	return _u
}

// RemoveCategorySpecIDs removes the "category_specs" edge to CategorySpec entities by IDs.
func (_u *MenuCategoryUpdate) RemoveCategorySpecIDs(ids ...uint64) *MenuCategoryUpdate {
	_u.mutation.RemoveCategorySpecIDs(ids...)
	return _u
}

// RemoveCategorySpecs removes "category_specs" edges to CategorySpec entities.
func (_u *MenuCategoryUpdate) RemoveCategorySpecs(v ...*CategorySpec) *MenuCategoryUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCategorySpecIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MenuCategoryUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MenuCategoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MenuCategoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MenuCategoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MenuCategoryUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if menucategory.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized menucategory.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := menucategory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *MenuCategoryUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := menucategory.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MenuCategory.name": %w`, err)}
		}
	}
	return nil
}

func (_u *MenuCategoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(menucategory.Table, menucategory.Columns, sqlgraph.NewFieldSpec(menucategory.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(menucategory.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeleteTs(); ok {
		_spec.SetField(menucategory.FieldDeleteTs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeleteTs(); ok {
		_spec.AddField(menucategory.FieldDeleteTs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(menucategory.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(menucategory.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(menucategory.FieldDescription, field.TypeString)
	}
	if _u.mutation.MenusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   menucategory.MenusTable,
			Columns: []string{menucategory.MenusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menu.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMenusIDs(); len(nodes) > 0 && !_u.mutation.MenusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   menucategory.MenusTable,
			Columns: []string{menucategory.MenusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menu.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MenusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   menucategory.MenusTable,
			Columns: []string{menucategory.MenusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menu.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CategorySpecsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   menucategory.CategorySpecsTable,
			Columns: []string{menucategory.CategorySpecsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(categoryspec.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCategorySpecsIDs(); len(nodes) > 0 && !_u.mutation.CategorySpecsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   menucategory.CategorySpecsTable,
			Columns: []string{menucategory.CategorySpecsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(categoryspec.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategorySpecsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   menucategory.CategorySpecsTable,
			Columns: []string{menucategory.CategorySpecsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(categoryspec.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{menucategory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MenuCategoryUpdateOne is the builder for updating a single MenuCategory entity.
type MenuCategoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MenuCategoryMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MenuCategoryUpdateOne) SetUpdatedAt(v time.Time) *MenuCategoryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeleteTs sets the "delete_ts" field.
func (_u *MenuCategoryUpdateOne) SetDeleteTs(v int64) *MenuCategoryUpdateOne {
	_u.mutation.ResetDeleteTs()
	_u.mutation.SetDeleteTs(v)
	return _u
}

// SetNillableDeleteTs sets the "delete_ts" field if the given value is not nil.
func (_u *MenuCategoryUpdateOne) SetNillableDeleteTs(v *int64) *MenuCategoryUpdateOne {
	if v != nil {
		_u.SetDeleteTs(*v)
	}
	return _u
}

// AddDeleteTs adds value to the "delete_ts" field.
func (_u *MenuCategoryUpdateOne) AddDeleteTs(v int64) *MenuCategoryUpdateOne {
	_u.mutation.AddDeleteTs(v)
	return _u
}

// SetName sets the "name" field.
func (_u *MenuCategoryUpdateOne) SetName(v string) *MenuCategoryUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MenuCategoryUpdateOne) SetNillableName(v *string) *MenuCategoryUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *MenuCategoryUpdateOne) SetDescription(v string) *MenuCategoryUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *MenuCategoryUpdateOne) SetNillableDescription(v *string) *MenuCategoryUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *MenuCategoryUpdateOne) ClearDescription() *MenuCategoryUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// AddMenuIDs adds the "menus" edge to the Menu entity by IDs.
func (_u *MenuCategoryUpdateOne) AddMenuIDs(ids ...uint64) *MenuCategoryUpdateOne {
	_u.mutation.AddMenuIDs(ids...)
	return _u
}

// AddMenus adds the "menus" edges to the Menu entity.
func (_u *MenuCategoryUpdateOne) AddMenus(v ...*Menu) *MenuCategoryUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMenuIDs(ids...)
}

// AddCategorySpecIDs adds the "category_specs" edge to the CategorySpec entity by IDs.
func (_u *MenuCategoryUpdateOne) AddCategorySpecIDs(ids ...uint64) *MenuCategoryUpdateOne {
	_u.mutation.AddCategorySpecIDs(ids...)
	return _u
}

// AddCategorySpecs adds the "category_specs" edges to the CategorySpec entity.
func (_u *MenuCategoryUpdateOne) AddCategorySpecs(v ...*CategorySpec) *MenuCategoryUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCategorySpecIDs(ids...)
}

// Mutation returns the MenuCategoryMutation object of the builder.
func (_u *MenuCategoryUpdateOne) Mutation() *MenuCategoryMutation {
	return _u.mutation
}

// ClearMenus clears all "menus" edges to the Menu entity.
func (_u *MenuCategoryUpdateOne) ClearMenus() *MenuCategoryUpdateOne {
	_u.mutation.ClearMenus()
	return _u
}

// RemoveMenuIDs removes the "menus" edge to Menu entities by IDs.
func (_u *MenuCategoryUpdateOne) RemoveMenuIDs(ids ...uint64) *MenuCategoryUpdateOne {
	_u.mutation.RemoveMenuIDs(ids...)
	return _u
}

// RemoveMenus removes "menus" edges to Menu entities.
func (_u *MenuCategoryUpdateOne) RemoveMenus(v ...*Menu) *MenuCategoryUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMenuIDs(ids...)
}

// ClearCategorySpecs clears all "category_specs" edges to the CategorySpec entity.
func (_u *MenuCategoryUpdateOne) ClearCategorySpecs() *MenuCategoryUpdateOne {
	_u.mutation.ClearCategorySpecs()
	return _u
}

// RemoveCategorySpecIDs removes the "category_specs" edge to CategorySpec entities by IDs.
func (_u *MenuCategoryUpdateOne) RemoveCategorySpecIDs(ids ...uint64) *MenuCategoryUpdateOne {
	_u.mutation.RemoveCategorySpecIDs(ids...)
	return _u
}

// RemoveCategorySpecs removes "category_specs" edges to CategorySpec entities.
func (_u *MenuCategoryUpdateOne) RemoveCategorySpecs(v ...*CategorySpec) *MenuCategoryUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCategorySpecIDs(ids...)
}

// Where appends a list predicates to the MenuCategoryUpdate builder.
func (_u *MenuCategoryUpdateOne) Where(ps ...predicate.MenuCategory) *MenuCategoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MenuCategoryUpdateOne) Select(field string, fields ...string) *MenuCategoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MenuCategory entity.
func (_u *MenuCategoryUpdateOne) Save(ctx context.Context) (*MenuCategory, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MenuCategoryUpdateOne) SaveX(ctx context.Context) *MenuCategory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MenuCategoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MenuCategoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MenuCategoryUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if menucategory.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized menucategory.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := menucategory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *MenuCategoryUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := menucategory.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MenuCategory.name": %w`, err)}
		}
	}
	return nil
}

func (_u *MenuCategoryUpdateOne) sqlSave(ctx context.Context) (_node *MenuCategory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(menucategory.Table, menucategory.Columns, sqlgraph.NewFieldSpec(menucategory.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MenuCategory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, menucategory.FieldID)
		for _, f := range fields {
			if !menucategory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != menucategory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(menucategory.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeleteTs(); ok {
		_spec.SetField(menucategory.FieldDeleteTs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeleteTs(); ok {
		_spec.AddField(menucategory.FieldDeleteTs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(menucategory.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(menucategory.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(menucategory.FieldDescription, field.TypeString)
	}
	if _u.mutation.MenusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   menucategory.MenusTable,
			Columns: []string{menucategory.MenusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menu.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMenusIDs(); len(nodes) > 0 && !_u.mutation.MenusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   menucategory.MenusTable,
			Columns: []string{menucategory.MenusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menu.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MenusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   menucategory.MenusTable,
			Columns: []string{menucategory.MenusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menu.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CategorySpecsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   menucategory.CategorySpecsTable,
			Columns: []string{menucategory.CategorySpecsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(categoryspec.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCategorySpecsIDs(); len(nodes) > 0 && !_u.mutation.CategorySpecsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   menucategory.CategorySpecsTable,
			Columns: []string{menucategory.CategorySpecsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(categoryspec.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategorySpecsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   menucategory.CategorySpecsTable,
			Columns: []string{menucategory.CategorySpecsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(categoryspec.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MenuCategory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{menucategory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
