// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/solikewind/happyeat/dal/model/ent/object"
)

// 对象元数据表
type Object struct {
	config `json:"-"`
	// ID of the ent.
	// ID
	ID uint64 `json:"id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 删除时间戳
	DeleteTs int64 `json:"delete_ts,omitempty"`
	// 原始文件名
	Name string `json:"name,omitempty"`
	// 对象存储 key
	Key string `json:"key,omitempty"`
	// 访问 URL
	URL string `json:"url,omitempty"`
	// 内容类型
	ContentType *string `json:"content_type,omitempty"`
	// 文件后缀
	Suffix *string `json:"suffix,omitempty"`
	// 文件大小（字节）
	Size int64 `json:"size,omitempty"`
	// 内容哈希（murmur3）
	Hash string `json:"hash,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ObjectQuery when eager-loading is set.
	Edges        ObjectEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ObjectEdges holds the relations/edges for other nodes in the graph.
type ObjectEdges struct {
	// MenuCovers holds the value of the menu_covers edge.
	MenuCovers []*Menu `json:"menu_covers,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MenuCoversOrErr returns the MenuCovers value or an error if the edge
// was not loaded in eager-loading.
func (e ObjectEdges) MenuCoversOrErr() ([]*Menu, error) {
	if e.loadedTypes[0] {
		return e.MenuCovers, nil
	}
	return nil, &NotLoadedError{edge: "menu_covers"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Object) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case object.FieldID, object.FieldDeleteTs, object.FieldSize:
			values[i] = new(sql.NullInt64)
		case object.FieldName, object.FieldKey, object.FieldURL, object.FieldContentType, object.FieldSuffix, object.FieldHash:
			values[i] = new(sql.NullString)
		case object.FieldCreatedAt, object.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Object fields.
func (_m *Object) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case object.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case object.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case object.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case object.FieldDeleteTs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field delete_ts", values[i])
			} else if value.Valid {
				_m.DeleteTs = value.Int64
			}
		case object.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case object.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				_m.Key = value.String
			}
		case object.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case object.FieldContentType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_type", values[i])
			} else if value.Valid {
				_m.ContentType = new(string)
				*_m.ContentType = value.String
			}
		case object.FieldSuffix:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field suffix", values[i])
			} else if value.Valid {
				_m.Suffix = new(string)
				*_m.Suffix = value.String
			}
		case object.FieldSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size", values[i])
			} else if value.Valid {
				_m.Size = value.Int64
			}
		case object.FieldHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hash", values[i])
			} else if value.Valid {
				_m.Hash = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Object.
// This includes values selected through modifiers, order, etc.
func (_m *Object) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMenuCovers queries the "menu_covers" edge of the Object entity.
func (_m *Object) QueryMenuCovers() *MenuQuery {
	return NewObjectClient(_m.config).QueryMenuCovers(_m)
}

// Update returns a builder for updating this Object.
// Note that you need to call Object.Unwrap() before calling this method if this Object
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Object) Update() *ObjectUpdateOne {
	return NewObjectClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Object entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Object) Unwrap() *Object {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Object is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Object) String() string {
	var builder strings.Builder
	builder.WriteString("Object(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("delete_ts=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeleteTs))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("key=")
	builder.WriteString(_m.Key)
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	if v := _m.ContentType; v != nil {
		builder.WriteString("content_type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Suffix; v != nil {
		builder.WriteString("suffix=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("size=")
	builder.WriteString(fmt.Sprintf("%v", _m.Size))
	builder.WriteString(", ")
	builder.WriteString("hash=")
	builder.WriteString(_m.Hash)
	builder.WriteByte(')')
	return builder.String()
}

// Objects is a parsable slice of Object.
type Objects []*Object
