// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/solikewind/happyeat/dal/model/ent/operationlog"
)

// OperationLogCreate is the builder for creating a OperationLog entity.
type OperationLogCreate struct {
	config
	mutation *OperationLogMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *OperationLogCreate) SetCreatedAt(v time.Time) *OperationLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OperationLogCreate) SetNillableCreatedAt(v *time.Time) *OperationLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OperationLogCreate) SetUpdatedAt(v time.Time) *OperationLogCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OperationLogCreate) SetNillableUpdatedAt(v *time.Time) *OperationLogCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetActorUserCode sets the "actor_user_code" field.
func (_c *OperationLogCreate) SetActorUserCode(v string) *OperationLogCreate {
	_c.mutation.SetActorUserCode(v)
	return _c
}

// SetModule sets the "module" field.
func (_c *OperationLogCreate) SetModule(v string) *OperationLogCreate {
	_c.mutation.SetModule(v)
	return _c
}

// SetAction sets the "action" field.
func (_c *OperationLogCreate) SetAction(v string) *OperationLogCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetMethod sets the "method" field.
func (_c *OperationLogCreate) SetMethod(v string) *OperationLogCreate {
	_c.mutation.SetMethod(v)
	return _c
}

// SetPath sets the "path" field.
func (_c *OperationLogCreate) SetPath(v string) *OperationLogCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetNormalizedPath sets the "normalized_path" field.
func (_c *OperationLogCreate) SetNormalizedPath(v string) *OperationLogCreate {
	_c.mutation.SetNormalizedPath(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *OperationLogCreate) SetStatus(v int) *OperationLogCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *OperationLogCreate) SetNillableStatus(v *int) *OperationLogCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetTargetID sets the "target_id" field.
func (_c *OperationLogCreate) SetTargetID(v string) *OperationLogCreate {
	_c.mutation.SetTargetID(v)
	return _c
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_c *OperationLogCreate) SetNillableTargetID(v *string) *OperationLogCreate {
	if v != nil {
		_c.SetTargetID(*v)
	}
	return _c
}

// SetIP sets the "ip" field.
func (_c *OperationLogCreate) SetIP(v string) *OperationLogCreate {
	_c.mutation.SetIP(v)
	return _c
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_c *OperationLogCreate) SetNillableIP(v *string) *OperationLogCreate {
	if v != nil {
		_c.SetIP(*v)
	}
	return _c
}

// SetUserAgent sets the "user_agent" field.
func (_c *OperationLogCreate) SetUserAgent(v string) *OperationLogCreate {
	_c.mutation.SetUserAgent(v)
	return _c
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_c *OperationLogCreate) SetNillableUserAgent(v *string) *OperationLogCreate {
	if v != nil {
		_c.SetUserAgent(*v)
	}
	return _c
}

// SetSummary sets the "summary" field.
func (_c *OperationLogCreate) SetSummary(v string) *OperationLogCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_c *OperationLogCreate) SetNillableSummary(v *string) *OperationLogCreate {
	if v != nil {
		_c.SetSummary(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OperationLogCreate) SetID(v uint64) *OperationLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the OperationLogMutation object of the builder.
func (_c *OperationLogCreate) Mutation() *OperationLogMutation {
	return _c.mutation
}

// Save creates the OperationLog in the database.
func (_c *OperationLogCreate) Save(ctx context.Context) (*OperationLog, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OperationLogCreate) SaveX(ctx context.Context) *OperationLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OperationLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OperationLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OperationLogCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if operationlog.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized operationlog.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := operationlog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if operationlog.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized operationlog.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := operationlog.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := operationlog.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.TargetID(); !ok {
		v := operationlog.DefaultTargetID
		_c.mutation.SetTargetID(v)
	}
	if _, ok := _c.mutation.IP(); !ok {
		v := operationlog.DefaultIP
		_c.mutation.SetIP(v)
	}
	if _, ok := _c.mutation.UserAgent(); !ok {
		v := operationlog.DefaultUserAgent
		_c.mutation.SetUserAgent(v)
	}
	if _, ok := _c.mutation.Summary(); !ok {
		v := operationlog.DefaultSummary
		_c.mutation.SetSummary(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *OperationLogCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OperationLog.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OperationLog.updated_at"`)}
	}
	if _, ok := _c.mutation.ActorUserCode(); !ok {
		return &ValidationError{Name: "actor_user_code", err: errors.New(`ent: missing required field "OperationLog.actor_user_code"`)}
	}
	if v, ok := _c.mutation.ActorUserCode(); ok {
		if err := operationlog.ActorUserCodeValidator(v); err != nil {
			return &ValidationError{Name: "actor_user_code", err: fmt.Errorf(`ent: validator failed for field "OperationLog.actor_user_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Module(); !ok {
		return &ValidationError{Name: "module", err: errors.New(`ent: missing required field "OperationLog.module"`)}
	}
	if v, ok := _c.mutation.Module(); ok {
		if err := operationlog.ModuleValidator(v); err != nil {
			return &ValidationError{Name: "module", err: fmt.Errorf(`ent: validator failed for field "OperationLog.module": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "OperationLog.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := operationlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "OperationLog.action": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Method(); !ok {
		return &ValidationError{Name: "method", err: errors.New(`ent: missing required field "OperationLog.method"`)}
	}
	if v, ok := _c.mutation.Method(); ok {
		if err := operationlog.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "OperationLog.method": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "OperationLog.path"`)}
	}
	if v, ok := _c.mutation.Path(); ok {
		if err := operationlog.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "OperationLog.path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NormalizedPath(); !ok {
		return &ValidationError{Name: "normalized_path", err: errors.New(`ent: missing required field "OperationLog.normalized_path"`)}
	}
	if v, ok := _c.mutation.NormalizedPath(); ok {
		if err := operationlog.NormalizedPathValidator(v); err != nil {
			return &ValidationError{Name: "normalized_path", err: fmt.Errorf(`ent: validator failed for field "OperationLog.normalized_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "OperationLog.status"`)}
	}
	if _, ok := _c.mutation.TargetID(); !ok {
		return &ValidationError{Name: "target_id", err: errors.New(`ent: missing required field "OperationLog.target_id"`)}
	}
	if v, ok := _c.mutation.TargetID(); ok {
		if err := operationlog.TargetIDValidator(v); err != nil {
			return &ValidationError{Name: "target_id", err: fmt.Errorf(`ent: validator failed for field "OperationLog.target_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IP(); !ok {
		return &ValidationError{Name: "ip", err: errors.New(`ent: missing required field "OperationLog.ip"`)}
	}
	if v, ok := _c.mutation.IP(); ok {
		if err := operationlog.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "OperationLog.ip": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserAgent(); !ok {
		return &ValidationError{Name: "user_agent", err: errors.New(`ent: missing required field "OperationLog.user_agent"`)}
	}
	if v, ok := _c.mutation.UserAgent(); ok {
		if err := operationlog.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "OperationLog.user_agent": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Summary(); !ok {
		return &ValidationError{Name: "summary", err: errors.New(`ent: missing required field "OperationLog.summary"`)}
	}
	if v, ok := _c.mutation.Summary(); ok {
		if err := operationlog.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "OperationLog.summary": %w`, err)}
		}
	}
	return nil
}

func (_c *OperationLogCreate) sqlSave(ctx context.Context) (*OperationLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OperationLogCreate) createSpec() (*OperationLog, *sqlgraph.CreateSpec) {
	var (
		_node = &OperationLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(operationlog.Table, sqlgraph.NewFieldSpec(operationlog.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(operationlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(operationlog.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ActorUserCode(); ok {
		_spec.SetField(operationlog.FieldActorUserCode, field.TypeString, value)
		_node.ActorUserCode = value
	}
	if value, ok := _c.mutation.Module(); ok {
		_spec.SetField(operationlog.FieldModule, field.TypeString, value)
		_node.Module = value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(operationlog.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.Method(); ok {
		_spec.SetField(operationlog.FieldMethod, field.TypeString, value)
		_node.Method = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(operationlog.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.NormalizedPath(); ok {
		_spec.SetField(operationlog.FieldNormalizedPath, field.TypeString, value)
		_node.NormalizedPath = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(operationlog.FieldStatus, field.TypeInt, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.TargetID(); ok {
		_spec.SetField(operationlog.FieldTargetID, field.TypeString, value)
		_node.TargetID = value
	}
	if value, ok := _c.mutation.IP(); ok {
		_spec.SetField(operationlog.FieldIP, field.TypeString, value)
		_node.IP = value
	}
	if value, ok := _c.mutation.UserAgent(); ok {
		_spec.SetField(operationlog.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(operationlog.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	return _node, _spec
}

// OperationLogCreateBulk is the builder for creating many OperationLog entities in bulk.
type OperationLogCreateBulk struct {
	config
	err      error
	builders []*OperationLogCreate
}

// Save creates the OperationLog entities in the database.
func (_c *OperationLogCreateBulk) Save(ctx context.Context) ([]*OperationLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OperationLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OperationLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OperationLogCreateBulk) SaveX(ctx context.Context) []*OperationLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OperationLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OperationLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
