// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/solikewind/happyeat/dal/model/ent/operationlog"
)

// 后台操作审计日志
type OperationLog struct {
	config `json:"-"`
	// ID of the ent.
	// ID
	ID uint64 `json:"id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 操作者 user_code
	ActorUserCode string `json:"actor_user_code,omitempty"`
	// 业务模块
	Module string `json:"module,omitempty"`
	// 动作
	Action string `json:"action,omitempty"`
	// HTTP 方法
	Method string `json:"method,omitempty"`
	// 原始请求路径
	Path string `json:"path,omitempty"`
	// 归一化路径
	NormalizedPath string `json:"normalized_path,omitempty"`
	// 响应状态码
	Status int `json:"status,omitempty"`
	// 目标 ID（从路径提取，可能为空）
	TargetID string `json:"target_id,omitempty"`
	// 客户端 IP
	IP string `json:"ip,omitempty"`
	// User-Agent
	UserAgent string `json:"user_agent,omitempty"`
	// 操作摘要
	Summary      string `json:"summary,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OperationLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case operationlog.FieldID, operationlog.FieldStatus:
			values[i] = new(sql.NullInt64)
		case operationlog.FieldActorUserCode, operationlog.FieldModule, operationlog.FieldAction, operationlog.FieldMethod, operationlog.FieldPath, operationlog.FieldNormalizedPath, operationlog.FieldTargetID, operationlog.FieldIP, operationlog.FieldUserAgent, operationlog.FieldSummary:
			values[i] = new(sql.NullString)
		case operationlog.FieldCreatedAt, operationlog.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OperationLog fields.
func (_m *OperationLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case operationlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case operationlog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case operationlog.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case operationlog.FieldActorUserCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actor_user_code", values[i])
			} else if value.Valid {
				_m.ActorUserCode = value.String
			}
		case operationlog.FieldModule:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field module", values[i])
			} else if value.Valid {
				_m.Module = value.String
			}
		case operationlog.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = value.String
			}
		case operationlog.FieldMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field method", values[i])
			} else if value.Valid {
				_m.Method = value.String
			}
		case operationlog.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = value.String
			}
		case operationlog.FieldNormalizedPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field normalized_path", values[i])
			} else if value.Valid {
				_m.NormalizedPath = value.String
			}
		case operationlog.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = int(value.Int64)
			}
		case operationlog.FieldTargetID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_id", values[i])
			} else if value.Valid {
				_m.TargetID = value.String
			}
		case operationlog.FieldIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip", values[i])
			} else if value.Valid {
				_m.IP = value.String
			}
		case operationlog.FieldUserAgent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_agent", values[i])
			} else if value.Valid {
				_m.UserAgent = value.String
			}
		case operationlog.FieldSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field summary", values[i])
			} else if value.Valid {
				_m.Summary = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OperationLog.
// This includes values selected through modifiers, order, etc.
func (_m *OperationLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OperationLog.
// Note that you need to call OperationLog.Unwrap() before calling this method if this OperationLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OperationLog) Update() *OperationLogUpdateOne {
	return NewOperationLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OperationLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OperationLog) Unwrap() *OperationLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OperationLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OperationLog) String() string {
	var builder strings.Builder
	builder.WriteString("OperationLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("actor_user_code=")
	builder.WriteString(_m.ActorUserCode)
	builder.WriteString(", ")
	builder.WriteString("module=")
	builder.WriteString(_m.Module)
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(_m.Action)
	builder.WriteString(", ")
	builder.WriteString("method=")
	builder.WriteString(_m.Method)
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(_m.Path)
	builder.WriteString(", ")
	builder.WriteString("normalized_path=")
	builder.WriteString(_m.NormalizedPath)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("target_id=")
	builder.WriteString(_m.TargetID)
	builder.WriteString(", ")
	builder.WriteString("ip=")
	builder.WriteString(_m.IP)
	builder.WriteString(", ")
	builder.WriteString("user_agent=")
	builder.WriteString(_m.UserAgent)
	builder.WriteString(", ")
	builder.WriteString("summary=")
	builder.WriteString(_m.Summary)
	builder.WriteByte(')')
	return builder.String()
}

// OperationLogs is a parsable slice of OperationLog.
type OperationLogs []*OperationLog
