// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/solikewind/happyeat/common/consts/enum"
	"github.com/solikewind/happyeat/dal/model/ent/order"
	"github.com/solikewind/happyeat/dal/model/ent/table"
)

// 订单表
type Order struct {
	config `json:"-"`
	// ID of the ent.
	// ID
	ID uint64 `json:"id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 删除时间戳
	DeleteTs int64 `json:"delete_ts,omitempty"`
	// 餐桌ID
	TableID *uint64 `json:"table_id,omitempty"`
	// 订单号
	OrderNo string `json:"order_no,omitempty"`
	// dine_in=堂食 takeaway=打包外带
	OrderType enum.OrderType `json:"order_type,omitempty"`
	// created=待支付 paid=已支付 preparing=制作中 completed=已完成 cancelled=已取消
	Status enum.OrderStatus `json:"status,omitempty"`
	// 订单总金额
	TotalAmount int64 `json:"total_amount,omitempty"`
	// 实收金额（分），可与总金额不同（抹零、优惠等）；未收款时可为 0
	ActualAmount int64 `json:"actual_amount,omitempty"`
	// 备注
	Remark *string `json:"remark,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OrderQuery when eager-loading is set.
	Edges        OrderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OrderEdges holds the relations/edges for other nodes in the graph.
type OrderEdges struct {
	// 堂食时关联餐桌，外带为空
	Table *Table `json:"table,omitempty"`
	// Items holds the value of the items edge.
	Items []*OrderItem `json:"items,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TableOrErr returns the Table value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OrderEdges) TableOrErr() (*Table, error) {
	if e.Table != nil {
		return e.Table, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: table.Label}
	}
	return nil, &NotLoadedError{edge: "table"}
}

// ItemsOrErr returns the Items value or an error if the edge
// was not loaded in eager-loading.
func (e OrderEdges) ItemsOrErr() ([]*OrderItem, error) {
	if e.loadedTypes[1] {
		return e.Items, nil
	}
	return nil, &NotLoadedError{edge: "items"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Order) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case order.FieldStatus:
			values[i] = new(enum.OrderStatus)
		case order.FieldOrderType:
			values[i] = new(enum.OrderType)
		case order.FieldID, order.FieldDeleteTs, order.FieldTableID, order.FieldTotalAmount, order.FieldActualAmount:
			values[i] = new(sql.NullInt64)
		case order.FieldOrderNo, order.FieldRemark:
			values[i] = new(sql.NullString)
		case order.FieldCreatedAt, order.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Order fields.
func (_m *Order) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case order.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case order.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case order.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case order.FieldDeleteTs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field delete_ts", values[i])
			} else if value.Valid {
				_m.DeleteTs = value.Int64
			}
		case order.FieldTableID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field table_id", values[i])
			} else if value.Valid {
				_m.TableID = new(uint64)
				*_m.TableID = uint64(value.Int64)
			}
		case order.FieldOrderNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field order_no", values[i])
			} else if value.Valid {
				_m.OrderNo = value.String
			}
		case order.FieldOrderType:
			if value, ok := values[i].(*enum.OrderType); !ok {
				return fmt.Errorf("unexpected type %T for field order_type", values[i])
			} else if value != nil {
				_m.OrderType = *value
			}
		case order.FieldStatus:
			if value, ok := values[i].(*enum.OrderStatus); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value != nil {
				_m.Status = *value
			}
		case order.FieldTotalAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_amount", values[i])
			} else if value.Valid {
				_m.TotalAmount = value.Int64
			}
		case order.FieldActualAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field actual_amount", values[i])
			} else if value.Valid {
				_m.ActualAmount = value.Int64
			}
		case order.FieldRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value.Valid {
				_m.Remark = new(string)
				*_m.Remark = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Order.
// This includes values selected through modifiers, order, etc.
func (_m *Order) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTable queries the "table" edge of the Order entity.
func (_m *Order) QueryTable() *TableQuery {
	return NewOrderClient(_m.config).QueryTable(_m)
}

// QueryItems queries the "items" edge of the Order entity.
func (_m *Order) QueryItems() *OrderItemQuery {
	return NewOrderClient(_m.config).QueryItems(_m)
}

// Update returns a builder for updating this Order.
// Note that you need to call Order.Unwrap() before calling this method if this Order
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Order) Update() *OrderUpdateOne {
	return NewOrderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Order entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Order) Unwrap() *Order {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Order is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Order) String() string {
	var builder strings.Builder
	builder.WriteString("Order(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("delete_ts=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeleteTs))
	builder.WriteString(", ")
	if v := _m.TableID; v != nil {
		builder.WriteString("table_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("order_no=")
	builder.WriteString(_m.OrderNo)
	builder.WriteString(", ")
	builder.WriteString("order_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderType))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("total_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalAmount))
	builder.WriteString(", ")
	builder.WriteString("actual_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActualAmount))
	builder.WriteString(", ")
	if v := _m.Remark; v != nil {
		builder.WriteString("remark=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// Orders is a parsable slice of Order.
type Orders []*Order
