// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/solikewind/happyeat/dal/model/ent/order"
	"github.com/solikewind/happyeat/dal/model/ent/orderitem"
	"github.com/solikewind/happyeat/dal/model/ent/predicate"
	"github.com/solikewind/happyeat/dal/model/ent/table"
)

// OrderUpdate is the builder for updating Order entities.
type OrderUpdate struct {
	config
	hooks    []Hook
	mutation *OrderMutation
}

// Where appends a list predicates to the OrderUpdate builder.
func (_u *OrderUpdate) Where(ps ...predicate.Order) *OrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrderNo sets the "order_no" field.
func (_u *OrderUpdate) SetOrderNo(v string) *OrderUpdate {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableOrderNo(v *string) *OrderUpdate {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetOrderType sets the "order_type" field.
func (_u *OrderUpdate) SetOrderType(v string) *OrderUpdate {
	_u.mutation.SetOrderType(v)
	return _u
}

// SetNillableOrderType sets the "order_type" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableOrderType(v *string) *OrderUpdate {
	if v != nil {
		_u.SetOrderType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrderUpdate) SetStatus(v string) *OrderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableStatus(v *string) *OrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTotalAmount sets the "total_amount" field.
func (_u *OrderUpdate) SetTotalAmount(v float64) *OrderUpdate {
	_u.mutation.ResetTotalAmount()
	_u.mutation.SetTotalAmount(v)
	return _u
}

// SetNillableTotalAmount sets the "total_amount" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableTotalAmount(v *float64) *OrderUpdate {
	if v != nil {
		_u.SetTotalAmount(*v)
	}
	return _u
}

// AddTotalAmount adds value to the "total_amount" field.
func (_u *OrderUpdate) AddTotalAmount(v float64) *OrderUpdate {
	_u.mutation.AddTotalAmount(v)
	return _u
}

// SetRemark sets the "remark" field.
func (_u *OrderUpdate) SetRemark(v string) *OrderUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableRemark(v *string) *OrderUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *OrderUpdate) ClearRemark() *OrderUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrderUpdate) SetUpdatedAt(v time.Time) *OrderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTableID sets the "table" edge to the Table entity by ID.
func (_u *OrderUpdate) SetTableID(id int) *OrderUpdate {
	_u.mutation.SetTableID(id)
	return _u
}

// SetNillableTableID sets the "table" edge to the Table entity by ID if the given value is not nil.
func (_u *OrderUpdate) SetNillableTableID(id *int) *OrderUpdate {
	if id != nil {
		_u = _u.SetTableID(*id)
	}
	return _u
}

// SetTable sets the "table" edge to the Table entity.
func (_u *OrderUpdate) SetTable(v *Table) *OrderUpdate {
	return _u.SetTableID(v.ID)
}

// AddItemIDs adds the "items" edge to the OrderItem entity by IDs.
func (_u *OrderUpdate) AddItemIDs(ids ...int) *OrderUpdate {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the OrderItem entity.
func (_u *OrderUpdate) AddItems(v ...*OrderItem) *OrderUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// Mutation returns the OrderMutation object of the builder.
func (_u *OrderUpdate) Mutation() *OrderMutation {
	return _u.mutation
}

// ClearTable clears the "table" edge to the Table entity.
func (_u *OrderUpdate) ClearTable() *OrderUpdate {
	_u.mutation.ClearTable()
	return _u
}

// ClearItems clears all "items" edges to the OrderItem entity.
func (_u *OrderUpdate) ClearItems() *OrderUpdate {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to OrderItem entities by IDs.
func (_u *OrderUpdate) RemoveItemIDs(ids ...int) *OrderUpdate {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to OrderItem entities.
func (_u *OrderUpdate) RemoveItems(v ...*OrderItem) *OrderUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := order.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderUpdate) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := order.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "Order.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OrderType(); ok {
		if err := order.OrderTypeValidator(v); err != nil {
			return &ValidationError{Name: "order_type", err: fmt.Errorf(`ent: validator failed for field "Order.order_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := order.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Order.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Remark(); ok {
		if err := order.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "Order.remark": %w`, err)}
		}
	}
	return nil
}

func (_u *OrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(order.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.OrderType(); ok {
		_spec.SetField(order.FieldOrderType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalAmount(); ok {
		_spec.SetField(order.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalAmount(); ok {
		_spec.AddField(order.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(order.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(order.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(order.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TableCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.TableTable,
			Columns: []string{order.TableColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(table.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TableIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.TableTable,
			Columns: []string{order.TableColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(table.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.ItemsTable,
			Columns: []string{order.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.ItemsTable,
			Columns: []string{order.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.ItemsTable,
			Columns: []string{order.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrderUpdateOne is the builder for updating a single Order entity.
type OrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrderMutation
}

// SetOrderNo sets the "order_no" field.
func (_u *OrderUpdateOne) SetOrderNo(v string) *OrderUpdateOne {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableOrderNo(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetOrderType sets the "order_type" field.
func (_u *OrderUpdateOne) SetOrderType(v string) *OrderUpdateOne {
	_u.mutation.SetOrderType(v)
	return _u
}

// SetNillableOrderType sets the "order_type" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableOrderType(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetOrderType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrderUpdateOne) SetStatus(v string) *OrderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableStatus(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTotalAmount sets the "total_amount" field.
func (_u *OrderUpdateOne) SetTotalAmount(v float64) *OrderUpdateOne {
	_u.mutation.ResetTotalAmount()
	_u.mutation.SetTotalAmount(v)
	return _u
}

// SetNillableTotalAmount sets the "total_amount" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableTotalAmount(v *float64) *OrderUpdateOne {
	if v != nil {
		_u.SetTotalAmount(*v)
	}
	return _u
}

// AddTotalAmount adds value to the "total_amount" field.
func (_u *OrderUpdateOne) AddTotalAmount(v float64) *OrderUpdateOne {
	_u.mutation.AddTotalAmount(v)
	return _u
}

// SetRemark sets the "remark" field.
func (_u *OrderUpdateOne) SetRemark(v string) *OrderUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableRemark(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *OrderUpdateOne) ClearRemark() *OrderUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrderUpdateOne) SetUpdatedAt(v time.Time) *OrderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTableID sets the "table" edge to the Table entity by ID.
func (_u *OrderUpdateOne) SetTableID(id int) *OrderUpdateOne {
	_u.mutation.SetTableID(id)
	return _u
}

// SetNillableTableID sets the "table" edge to the Table entity by ID if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableTableID(id *int) *OrderUpdateOne {
	if id != nil {
		_u = _u.SetTableID(*id)
	}
	return _u
}

// SetTable sets the "table" edge to the Table entity.
func (_u *OrderUpdateOne) SetTable(v *Table) *OrderUpdateOne {
	return _u.SetTableID(v.ID)
}

// AddItemIDs adds the "items" edge to the OrderItem entity by IDs.
func (_u *OrderUpdateOne) AddItemIDs(ids ...int) *OrderUpdateOne {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the OrderItem entity.
func (_u *OrderUpdateOne) AddItems(v ...*OrderItem) *OrderUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// Mutation returns the OrderMutation object of the builder.
func (_u *OrderUpdateOne) Mutation() *OrderMutation {
	return _u.mutation
}

// ClearTable clears the "table" edge to the Table entity.
func (_u *OrderUpdateOne) ClearTable() *OrderUpdateOne {
	_u.mutation.ClearTable()
	return _u
}

// ClearItems clears all "items" edges to the OrderItem entity.
func (_u *OrderUpdateOne) ClearItems() *OrderUpdateOne {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to OrderItem entities by IDs.
func (_u *OrderUpdateOne) RemoveItemIDs(ids ...int) *OrderUpdateOne {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to OrderItem entities.
func (_u *OrderUpdateOne) RemoveItems(v ...*OrderItem) *OrderUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// Where appends a list predicates to the OrderUpdate builder.
func (_u *OrderUpdateOne) Where(ps ...predicate.Order) *OrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrderUpdateOne) Select(field string, fields ...string) *OrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Order entity.
func (_u *OrderUpdateOne) Save(ctx context.Context) (*Order, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderUpdateOne) SaveX(ctx context.Context) *Order {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := order.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderUpdateOne) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := order.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "Order.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OrderType(); ok {
		if err := order.OrderTypeValidator(v); err != nil {
			return &ValidationError{Name: "order_type", err: fmt.Errorf(`ent: validator failed for field "Order.order_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := order.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Order.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Remark(); ok {
		if err := order.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "Order.remark": %w`, err)}
		}
	}
	return nil
}

func (_u *OrderUpdateOne) sqlSave(ctx context.Context) (_node *Order, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Order.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, order.FieldID)
		for _, f := range fields {
			if !order.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != order.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(order.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.OrderType(); ok {
		_spec.SetField(order.FieldOrderType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalAmount(); ok {
		_spec.SetField(order.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalAmount(); ok {
		_spec.AddField(order.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(order.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(order.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(order.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TableCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.TableTable,
			Columns: []string{order.TableColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(table.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TableIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.TableTable,
			Columns: []string{order.TableColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(table.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.ItemsTable,
			Columns: []string{order.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.ItemsTable,
			Columns: []string{order.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.ItemsTable,
			Columns: []string{order.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Order{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
