// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/solikewind/happyeat/dal/model/ent/menuspec"
	"github.com/solikewind/happyeat/dal/model/ent/predicate"
	"github.com/solikewind/happyeat/dal/model/ent/specgroup"
	"github.com/solikewind/happyeat/dal/model/ent/specitem"
)

// SpecItemUpdate is the builder for updating SpecItem entities.
type SpecItemUpdate struct {
	config
	hooks    []Hook
	mutation *SpecItemMutation
}

// Where appends a list predicates to the SpecItemUpdate builder.
func (_u *SpecItemUpdate) Where(ps ...predicate.SpecItem) *SpecItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SpecItemUpdate) SetUpdatedAt(v time.Time) *SpecItemUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeleteTs sets the "delete_ts" field.
func (_u *SpecItemUpdate) SetDeleteTs(v int64) *SpecItemUpdate {
	_u.mutation.ResetDeleteTs()
	_u.mutation.SetDeleteTs(v)
	return _u
}

// SetNillableDeleteTs sets the "delete_ts" field if the given value is not nil.
func (_u *SpecItemUpdate) SetNillableDeleteTs(v *int64) *SpecItemUpdate {
	if v != nil {
		_u.SetDeleteTs(*v)
	}
	return _u
}

// AddDeleteTs adds value to the "delete_ts" field.
func (_u *SpecItemUpdate) AddDeleteTs(v int64) *SpecItemUpdate {
	_u.mutation.AddDeleteTs(v)
	return _u
}

// SetSpecGroupID sets the "spec_group_id" field.
func (_u *SpecItemUpdate) SetSpecGroupID(v uint64) *SpecItemUpdate {
	_u.mutation.SetSpecGroupID(v)
	return _u
}

// SetNillableSpecGroupID sets the "spec_group_id" field if the given value is not nil.
func (_u *SpecItemUpdate) SetNillableSpecGroupID(v *uint64) *SpecItemUpdate {
	if v != nil {
		_u.SetSpecGroupID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *SpecItemUpdate) SetName(v string) *SpecItemUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SpecItemUpdate) SetNillableName(v *string) *SpecItemUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDefaultPrice sets the "default_price" field.
func (_u *SpecItemUpdate) SetDefaultPrice(v float64) *SpecItemUpdate {
	_u.mutation.ResetDefaultPrice()
	_u.mutation.SetDefaultPrice(v)
	return _u
}

// SetNillableDefaultPrice sets the "default_price" field if the given value is not nil.
func (_u *SpecItemUpdate) SetNillableDefaultPrice(v *float64) *SpecItemUpdate {
	if v != nil {
		_u.SetDefaultPrice(*v)
	}
	return _u
}

// AddDefaultPrice adds value to the "default_price" field.
func (_u *SpecItemUpdate) AddDefaultPrice(v float64) *SpecItemUpdate {
	_u.mutation.AddDefaultPrice(v)
	return _u
}

// SetSpecGroup sets the "spec_group" edge to the SpecGroup entity.
func (_u *SpecItemUpdate) SetSpecGroup(v *SpecGroup) *SpecItemUpdate {
	return _u.SetSpecGroupID(v.ID)
}

// AddMenuSpecIDs adds the "menu_specs" edge to the MenuSpec entity by IDs.
func (_u *SpecItemUpdate) AddMenuSpecIDs(ids ...uint64) *SpecItemUpdate {
	_u.mutation.AddMenuSpecIDs(ids...)
	return _u
}

// AddMenuSpecs adds the "menu_specs" edges to the MenuSpec entity.
func (_u *SpecItemUpdate) AddMenuSpecs(v ...*MenuSpec) *SpecItemUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMenuSpecIDs(ids...)
}

// Mutation returns the SpecItemMutation object of the builder.
func (_u *SpecItemUpdate) Mutation() *SpecItemMutation {
	return _u.mutation
}

// ClearSpecGroup clears the "spec_group" edge to the SpecGroup entity.
func (_u *SpecItemUpdate) ClearSpecGroup() *SpecItemUpdate {
	_u.mutation.ClearSpecGroup()
	return _u
}

// ClearMenuSpecs clears all "menu_specs" edges to the MenuSpec entity.
func (_u *SpecItemUpdate) ClearMenuSpecs() *SpecItemUpdate {
	_u.mutation.ClearMenuSpecs()
	return _u
}

// RemoveMenuSpecIDs removes the "menu_specs" edge to MenuSpec entities by IDs.
func (_u *SpecItemUpdate) RemoveMenuSpecIDs(ids ...uint64) *SpecItemUpdate {
	_u.mutation.RemoveMenuSpecIDs(ids...)
	return _u
}

// RemoveMenuSpecs removes "menu_specs" edges to MenuSpec entities.
func (_u *SpecItemUpdate) RemoveMenuSpecs(v ...*MenuSpec) *SpecItemUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMenuSpecIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SpecItemUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SpecItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SpecItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SpecItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SpecItemUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if specitem.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized specitem.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := specitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *SpecItemUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := specitem.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SpecItem.name": %w`, err)}
		}
	}
	if _u.mutation.SpecGroupCleared() && len(_u.mutation.SpecGroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SpecItem.spec_group"`)
	}
	return nil
}

func (_u *SpecItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(specitem.Table, specitem.Columns, sqlgraph.NewFieldSpec(specitem.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(specitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeleteTs(); ok {
		_spec.SetField(specitem.FieldDeleteTs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeleteTs(); ok {
		_spec.AddField(specitem.FieldDeleteTs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(specitem.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DefaultPrice(); ok {
		_spec.SetField(specitem.FieldDefaultPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDefaultPrice(); ok {
		_spec.AddField(specitem.FieldDefaultPrice, field.TypeFloat64, value)
	}
	if _u.mutation.SpecGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   specitem.SpecGroupTable,
			Columns: []string{specitem.SpecGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(specgroup.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SpecGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   specitem.SpecGroupTable,
			Columns: []string{specitem.SpecGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(specgroup.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MenuSpecsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   specitem.MenuSpecsTable,
			Columns: []string{specitem.MenuSpecsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menuspec.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMenuSpecsIDs(); len(nodes) > 0 && !_u.mutation.MenuSpecsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   specitem.MenuSpecsTable,
			Columns: []string{specitem.MenuSpecsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menuspec.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MenuSpecsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   specitem.MenuSpecsTable,
			Columns: []string{specitem.MenuSpecsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menuspec.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{specitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SpecItemUpdateOne is the builder for updating a single SpecItem entity.
type SpecItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SpecItemMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SpecItemUpdateOne) SetUpdatedAt(v time.Time) *SpecItemUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeleteTs sets the "delete_ts" field.
func (_u *SpecItemUpdateOne) SetDeleteTs(v int64) *SpecItemUpdateOne {
	_u.mutation.ResetDeleteTs()
	_u.mutation.SetDeleteTs(v)
	return _u
}

// SetNillableDeleteTs sets the "delete_ts" field if the given value is not nil.
func (_u *SpecItemUpdateOne) SetNillableDeleteTs(v *int64) *SpecItemUpdateOne {
	if v != nil {
		_u.SetDeleteTs(*v)
	}
	return _u
}

// AddDeleteTs adds value to the "delete_ts" field.
func (_u *SpecItemUpdateOne) AddDeleteTs(v int64) *SpecItemUpdateOne {
	_u.mutation.AddDeleteTs(v)
	return _u
}

// SetSpecGroupID sets the "spec_group_id" field.
func (_u *SpecItemUpdateOne) SetSpecGroupID(v uint64) *SpecItemUpdateOne {
	_u.mutation.SetSpecGroupID(v)
	return _u
}

// SetNillableSpecGroupID sets the "spec_group_id" field if the given value is not nil.
func (_u *SpecItemUpdateOne) SetNillableSpecGroupID(v *uint64) *SpecItemUpdateOne {
	if v != nil {
		_u.SetSpecGroupID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *SpecItemUpdateOne) SetName(v string) *SpecItemUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SpecItemUpdateOne) SetNillableName(v *string) *SpecItemUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDefaultPrice sets the "default_price" field.
func (_u *SpecItemUpdateOne) SetDefaultPrice(v float64) *SpecItemUpdateOne {
	_u.mutation.ResetDefaultPrice()
	_u.mutation.SetDefaultPrice(v)
	return _u
}

// SetNillableDefaultPrice sets the "default_price" field if the given value is not nil.
func (_u *SpecItemUpdateOne) SetNillableDefaultPrice(v *float64) *SpecItemUpdateOne {
	if v != nil {
		_u.SetDefaultPrice(*v)
	}
	return _u
}

// AddDefaultPrice adds value to the "default_price" field.
func (_u *SpecItemUpdateOne) AddDefaultPrice(v float64) *SpecItemUpdateOne {
	_u.mutation.AddDefaultPrice(v)
	return _u
}

// SetSpecGroup sets the "spec_group" edge to the SpecGroup entity.
func (_u *SpecItemUpdateOne) SetSpecGroup(v *SpecGroup) *SpecItemUpdateOne {
	return _u.SetSpecGroupID(v.ID)
}

// AddMenuSpecIDs adds the "menu_specs" edge to the MenuSpec entity by IDs.
func (_u *SpecItemUpdateOne) AddMenuSpecIDs(ids ...uint64) *SpecItemUpdateOne {
	_u.mutation.AddMenuSpecIDs(ids...)
	return _u
}

// AddMenuSpecs adds the "menu_specs" edges to the MenuSpec entity.
func (_u *SpecItemUpdateOne) AddMenuSpecs(v ...*MenuSpec) *SpecItemUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMenuSpecIDs(ids...)
}

// Mutation returns the SpecItemMutation object of the builder.
func (_u *SpecItemUpdateOne) Mutation() *SpecItemMutation {
	return _u.mutation
}

// ClearSpecGroup clears the "spec_group" edge to the SpecGroup entity.
func (_u *SpecItemUpdateOne) ClearSpecGroup() *SpecItemUpdateOne {
	_u.mutation.ClearSpecGroup()
	return _u
}

// ClearMenuSpecs clears all "menu_specs" edges to the MenuSpec entity.
func (_u *SpecItemUpdateOne) ClearMenuSpecs() *SpecItemUpdateOne {
	_u.mutation.ClearMenuSpecs()
	return _u
}

// RemoveMenuSpecIDs removes the "menu_specs" edge to MenuSpec entities by IDs.
func (_u *SpecItemUpdateOne) RemoveMenuSpecIDs(ids ...uint64) *SpecItemUpdateOne {
	_u.mutation.RemoveMenuSpecIDs(ids...)
	return _u
}

// RemoveMenuSpecs removes "menu_specs" edges to MenuSpec entities.
func (_u *SpecItemUpdateOne) RemoveMenuSpecs(v ...*MenuSpec) *SpecItemUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMenuSpecIDs(ids...)
}

// Where appends a list predicates to the SpecItemUpdate builder.
func (_u *SpecItemUpdateOne) Where(ps ...predicate.SpecItem) *SpecItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SpecItemUpdateOne) Select(field string, fields ...string) *SpecItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SpecItem entity.
func (_u *SpecItemUpdateOne) Save(ctx context.Context) (*SpecItem, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SpecItemUpdateOne) SaveX(ctx context.Context) *SpecItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SpecItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SpecItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SpecItemUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if specitem.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized specitem.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := specitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *SpecItemUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := specitem.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SpecItem.name": %w`, err)}
		}
	}
	if _u.mutation.SpecGroupCleared() && len(_u.mutation.SpecGroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SpecItem.spec_group"`)
	}
	return nil
}

func (_u *SpecItemUpdateOne) sqlSave(ctx context.Context) (_node *SpecItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(specitem.Table, specitem.Columns, sqlgraph.NewFieldSpec(specitem.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SpecItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, specitem.FieldID)
		for _, f := range fields {
			if !specitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != specitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(specitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeleteTs(); ok {
		_spec.SetField(specitem.FieldDeleteTs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeleteTs(); ok {
		_spec.AddField(specitem.FieldDeleteTs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(specitem.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DefaultPrice(); ok {
		_spec.SetField(specitem.FieldDefaultPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDefaultPrice(); ok {
		_spec.AddField(specitem.FieldDefaultPrice, field.TypeFloat64, value)
	}
	if _u.mutation.SpecGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   specitem.SpecGroupTable,
			Columns: []string{specitem.SpecGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(specgroup.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SpecGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   specitem.SpecGroupTable,
			Columns: []string{specitem.SpecGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(specgroup.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MenuSpecsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   specitem.MenuSpecsTable,
			Columns: []string{specitem.MenuSpecsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menuspec.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMenuSpecsIDs(); len(nodes) > 0 && !_u.mutation.MenuSpecsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   specitem.MenuSpecsTable,
			Columns: []string{specitem.MenuSpecsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menuspec.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MenuSpecsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   specitem.MenuSpecsTable,
			Columns: []string{specitem.MenuSpecsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menuspec.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SpecItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{specitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
