// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/solikewind/happyeat/dal/model/ent/menuspec"
	"github.com/solikewind/happyeat/dal/model/ent/predicate"
	"github.com/solikewind/happyeat/dal/model/ent/specgroup"
	"github.com/solikewind/happyeat/dal/model/ent/specitem"
)

// SpecItemQuery is the builder for querying SpecItem entities.
type SpecItemQuery struct {
	config
	ctx           *QueryContext
	order         []specitem.OrderOption
	inters        []Interceptor
	predicates    []predicate.SpecItem
	withSpecGroup *SpecGroupQuery
	withMenuSpecs *MenuSpecQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SpecItemQuery builder.
func (_q *SpecItemQuery) Where(ps ...predicate.SpecItem) *SpecItemQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *SpecItemQuery) Limit(limit int) *SpecItemQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *SpecItemQuery) Offset(offset int) *SpecItemQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *SpecItemQuery) Unique(unique bool) *SpecItemQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *SpecItemQuery) Order(o ...specitem.OrderOption) *SpecItemQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QuerySpecGroup chains the current query on the "spec_group" edge.
func (_q *SpecItemQuery) QuerySpecGroup() *SpecGroupQuery {
	query := (&SpecGroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(specitem.Table, specitem.FieldID, selector),
			sqlgraph.To(specgroup.Table, specgroup.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, specitem.SpecGroupTable, specitem.SpecGroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMenuSpecs chains the current query on the "menu_specs" edge.
func (_q *SpecItemQuery) QueryMenuSpecs() *MenuSpecQuery {
	query := (&MenuSpecClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(specitem.Table, specitem.FieldID, selector),
			sqlgraph.To(menuspec.Table, menuspec.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, specitem.MenuSpecsTable, specitem.MenuSpecsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SpecItem entity from the query.
// Returns a *NotFoundError when no SpecItem was found.
func (_q *SpecItemQuery) First(ctx context.Context) (*SpecItem, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{specitem.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *SpecItemQuery) FirstX(ctx context.Context) *SpecItem {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SpecItem ID from the query.
// Returns a *NotFoundError when no SpecItem ID was found.
func (_q *SpecItemQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{specitem.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *SpecItemQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SpecItem entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SpecItem entity is found.
// Returns a *NotFoundError when no SpecItem entities are found.
func (_q *SpecItemQuery) Only(ctx context.Context) (*SpecItem, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{specitem.Label}
	default:
		return nil, &NotSingularError{specitem.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *SpecItemQuery) OnlyX(ctx context.Context) *SpecItem {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SpecItem ID in the query.
// Returns a *NotSingularError when more than one SpecItem ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *SpecItemQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{specitem.Label}
	default:
		err = &NotSingularError{specitem.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *SpecItemQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SpecItems.
func (_q *SpecItemQuery) All(ctx context.Context) ([]*SpecItem, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SpecItem, *SpecItemQuery]()
	return withInterceptors[[]*SpecItem](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *SpecItemQuery) AllX(ctx context.Context) []*SpecItem {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SpecItem IDs.
func (_q *SpecItemQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(specitem.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *SpecItemQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *SpecItemQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*SpecItemQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *SpecItemQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *SpecItemQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *SpecItemQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SpecItemQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *SpecItemQuery) Clone() *SpecItemQuery {
	if _q == nil {
		return nil
	}
	return &SpecItemQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]specitem.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.SpecItem{}, _q.predicates...),
		withSpecGroup: _q.withSpecGroup.Clone(),
		withMenuSpecs: _q.withMenuSpecs.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithSpecGroup tells the query-builder to eager-load the nodes that are connected to
// the "spec_group" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SpecItemQuery) WithSpecGroup(opts ...func(*SpecGroupQuery)) *SpecItemQuery {
	query := (&SpecGroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSpecGroup = query
	return _q
}

// WithMenuSpecs tells the query-builder to eager-load the nodes that are connected to
// the "menu_specs" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SpecItemQuery) WithMenuSpecs(opts ...func(*MenuSpecQuery)) *SpecItemQuery {
	query := (&MenuSpecClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMenuSpecs = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SpecItem.Query().
//		GroupBy(specitem.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *SpecItemQuery) GroupBy(field string, fields ...string) *SpecItemGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SpecItemGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = specitem.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.SpecItem.Query().
//		Select(specitem.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *SpecItemQuery) Select(fields ...string) *SpecItemSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &SpecItemSelect{SpecItemQuery: _q}
	sbuild.label = specitem.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SpecItemSelect configured with the given aggregations.
func (_q *SpecItemQuery) Aggregate(fns ...AggregateFunc) *SpecItemSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *SpecItemQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !specitem.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *SpecItemQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SpecItem, error) {
	var (
		nodes       = []*SpecItem{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withSpecGroup != nil,
			_q.withMenuSpecs != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SpecItem).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SpecItem{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withSpecGroup; query != nil {
		if err := _q.loadSpecGroup(ctx, query, nodes, nil,
			func(n *SpecItem, e *SpecGroup) { n.Edges.SpecGroup = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withMenuSpecs; query != nil {
		if err := _q.loadMenuSpecs(ctx, query, nodes,
			func(n *SpecItem) { n.Edges.MenuSpecs = []*MenuSpec{} },
			func(n *SpecItem, e *MenuSpec) { n.Edges.MenuSpecs = append(n.Edges.MenuSpecs, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *SpecItemQuery) loadSpecGroup(ctx context.Context, query *SpecGroupQuery, nodes []*SpecItem, init func(*SpecItem), assign func(*SpecItem, *SpecGroup)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*SpecItem)
	for i := range nodes {
		fk := nodes[i].SpecGroupID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(specgroup.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "spec_group_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *SpecItemQuery) loadMenuSpecs(ctx context.Context, query *MenuSpecQuery, nodes []*SpecItem, init func(*SpecItem), assign func(*SpecItem, *MenuSpec)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uint64]*SpecItem)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(menuspec.FieldSpecItemID)
	}
	query.Where(predicate.MenuSpec(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(specitem.MenuSpecsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SpecItemID
		if fk == nil {
			return fmt.Errorf(`foreign-key "spec_item_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "spec_item_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *SpecItemQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *SpecItemQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(specitem.Table, specitem.Columns, sqlgraph.NewFieldSpec(specitem.FieldID, field.TypeUint64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, specitem.FieldID)
		for i := range fields {
			if fields[i] != specitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withSpecGroup != nil {
			_spec.Node.AddColumnOnce(specitem.FieldSpecGroupID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *SpecItemQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(specitem.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = specitem.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SpecItemGroupBy is the group-by builder for SpecItem entities.
type SpecItemGroupBy struct {
	selector
	build *SpecItemQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *SpecItemGroupBy) Aggregate(fns ...AggregateFunc) *SpecItemGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *SpecItemGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SpecItemQuery, *SpecItemGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *SpecItemGroupBy) sqlScan(ctx context.Context, root *SpecItemQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SpecItemSelect is the builder for selecting fields of SpecItem entities.
type SpecItemSelect struct {
	*SpecItemQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *SpecItemSelect) Aggregate(fns ...AggregateFunc) *SpecItemSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *SpecItemSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SpecItemQuery, *SpecItemSelect](ctx, _s.SpecItemQuery, _s, _s.inters, v)
}

func (_s *SpecItemSelect) sqlScan(ctx context.Context, root *SpecItemQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
