// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/solikewind/happyeat/dal/model/ent/order"
	"github.com/solikewind/happyeat/dal/model/ent/table"
	"github.com/solikewind/happyeat/dal/model/ent/tablecategory"
)

// TableCreate is the builder for creating a Table entity.
type TableCreate struct {
	config
	mutation *TableMutation
	hooks    []Hook
}

// SetCode sets the "code" field.
func (_c *TableCreate) SetCode(v string) *TableCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *TableCreate) SetStatus(v string) *TableCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TableCreate) SetNillableStatus(v *string) *TableCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCapacity sets the "capacity" field.
func (_c *TableCreate) SetCapacity(v int) *TableCreate {
	_c.mutation.SetCapacity(v)
	return _c
}

// SetNillableCapacity sets the "capacity" field if the given value is not nil.
func (_c *TableCreate) SetNillableCapacity(v *int) *TableCreate {
	if v != nil {
		_c.SetCapacity(*v)
	}
	return _c
}

// SetQrCode sets the "qr_code" field.
func (_c *TableCreate) SetQrCode(v string) *TableCreate {
	_c.mutation.SetQrCode(v)
	return _c
}

// SetNillableQrCode sets the "qr_code" field if the given value is not nil.
func (_c *TableCreate) SetNillableQrCode(v *string) *TableCreate {
	if v != nil {
		_c.SetQrCode(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TableCreate) SetCreatedAt(v time.Time) *TableCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TableCreate) SetNillableCreatedAt(v *time.Time) *TableCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TableCreate) SetUpdatedAt(v time.Time) *TableCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TableCreate) SetNillableUpdatedAt(v *time.Time) *TableCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCategoryID sets the "category" edge to the TableCategory entity by ID.
func (_c *TableCreate) SetCategoryID(id int) *TableCreate {
	_c.mutation.SetCategoryID(id)
	return _c
}

// SetCategory sets the "category" edge to the TableCategory entity.
func (_c *TableCreate) SetCategory(v *TableCategory) *TableCreate {
	return _c.SetCategoryID(v.ID)
}

// AddOrderIDs adds the "orders" edge to the Order entity by IDs.
func (_c *TableCreate) AddOrderIDs(ids ...int) *TableCreate {
	_c.mutation.AddOrderIDs(ids...)
	return _c
}

// AddOrders adds the "orders" edges to the Order entity.
func (_c *TableCreate) AddOrders(v ...*Order) *TableCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOrderIDs(ids...)
}

// Mutation returns the TableMutation object of the builder.
func (_c *TableCreate) Mutation() *TableMutation {
	return _c.mutation
}

// Save creates the Table in the database.
func (_c *TableCreate) Save(ctx context.Context) (*Table, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TableCreate) SaveX(ctx context.Context) *Table {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TableCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TableCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TableCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := table.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Capacity(); !ok {
		v := table.DefaultCapacity
		_c.mutation.SetCapacity(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := table.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := table.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TableCreate) check() error {
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Table.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := table.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Table.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Table.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := table.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Table.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Capacity(); !ok {
		return &ValidationError{Name: "capacity", err: errors.New(`ent: missing required field "Table.capacity"`)}
	}
	if v, ok := _c.mutation.QrCode(); ok {
		if err := table.QrCodeValidator(v); err != nil {
			return &ValidationError{Name: "qr_code", err: fmt.Errorf(`ent: validator failed for field "Table.qr_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Table.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Table.updated_at"`)}
	}
	if len(_c.mutation.CategoryIDs()) == 0 {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required edge "Table.category"`)}
	}
	return nil
}

func (_c *TableCreate) sqlSave(ctx context.Context) (*Table, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TableCreate) createSpec() (*Table, *sqlgraph.CreateSpec) {
	var (
		_node = &Table{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(table.Table, sqlgraph.NewFieldSpec(table.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(table.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(table.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Capacity(); ok {
		_spec.SetField(table.FieldCapacity, field.TypeInt, value)
		_node.Capacity = value
	}
	if value, ok := _c.mutation.QrCode(); ok {
		_spec.SetField(table.FieldQrCode, field.TypeString, value)
		_node.QrCode = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(table.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(table.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   table.CategoryTable,
			Columns: []string{table.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tablecategory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.table_category_tables = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   table.OrdersTable,
			Columns: []string{table.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TableCreateBulk is the builder for creating many Table entities in bulk.
type TableCreateBulk struct {
	config
	err      error
	builders []*TableCreate
}

// Save creates the Table entities in the database.
func (_c *TableCreateBulk) Save(ctx context.Context) ([]*Table, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Table, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TableMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TableCreateBulk) SaveX(ctx context.Context) []*Table {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TableCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TableCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
