// Code generated by ent, DO NOT EDIT.

package operationlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/solikewind/happyeat/dal/model/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEQ(FieldUpdatedAt, v))
}

// ActorUserCode applies equality check predicate on the "actor_user_code" field. It's identical to ActorUserCodeEQ.
func ActorUserCode(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEQ(FieldActorUserCode, v))
}

// Module applies equality check predicate on the "module" field. It's identical to ModuleEQ.
func Module(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEQ(FieldModule, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEQ(FieldAction, v))
}

// Method applies equality check predicate on the "method" field. It's identical to MethodEQ.
func Method(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEQ(FieldMethod, v))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEQ(FieldPath, v))
}

// NormalizedPath applies equality check predicate on the "normalized_path" field. It's identical to NormalizedPathEQ.
func NormalizedPath(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEQ(FieldNormalizedPath, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v int) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEQ(FieldStatus, v))
}

// TargetID applies equality check predicate on the "target_id" field. It's identical to TargetIDEQ.
func TargetID(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEQ(FieldTargetID, v))
}

// IP applies equality check predicate on the "ip" field. It's identical to IPEQ.
func IP(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEQ(FieldIP, v))
}

// UserAgent applies equality check predicate on the "user_agent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEQ(FieldUserAgent, v))
}

// Summary applies equality check predicate on the "summary" field. It's identical to SummaryEQ.
func Summary(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEQ(FieldSummary, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldLTE(FieldUpdatedAt, v))
}

// ActorUserCodeEQ applies the EQ predicate on the "actor_user_code" field.
func ActorUserCodeEQ(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEQ(FieldActorUserCode, v))
}

// ActorUserCodeNEQ applies the NEQ predicate on the "actor_user_code" field.
func ActorUserCodeNEQ(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldNEQ(FieldActorUserCode, v))
}

// ActorUserCodeIn applies the In predicate on the "actor_user_code" field.
func ActorUserCodeIn(vs ...string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldIn(FieldActorUserCode, vs...))
}

// ActorUserCodeNotIn applies the NotIn predicate on the "actor_user_code" field.
func ActorUserCodeNotIn(vs ...string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldNotIn(FieldActorUserCode, vs...))
}

// ActorUserCodeGT applies the GT predicate on the "actor_user_code" field.
func ActorUserCodeGT(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldGT(FieldActorUserCode, v))
}

// ActorUserCodeGTE applies the GTE predicate on the "actor_user_code" field.
func ActorUserCodeGTE(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldGTE(FieldActorUserCode, v))
}

// ActorUserCodeLT applies the LT predicate on the "actor_user_code" field.
func ActorUserCodeLT(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldLT(FieldActorUserCode, v))
}

// ActorUserCodeLTE applies the LTE predicate on the "actor_user_code" field.
func ActorUserCodeLTE(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldLTE(FieldActorUserCode, v))
}

// ActorUserCodeContains applies the Contains predicate on the "actor_user_code" field.
func ActorUserCodeContains(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldContains(FieldActorUserCode, v))
}

// ActorUserCodeHasPrefix applies the HasPrefix predicate on the "actor_user_code" field.
func ActorUserCodeHasPrefix(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldHasPrefix(FieldActorUserCode, v))
}

// ActorUserCodeHasSuffix applies the HasSuffix predicate on the "actor_user_code" field.
func ActorUserCodeHasSuffix(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldHasSuffix(FieldActorUserCode, v))
}

// ActorUserCodeEqualFold applies the EqualFold predicate on the "actor_user_code" field.
func ActorUserCodeEqualFold(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEqualFold(FieldActorUserCode, v))
}

// ActorUserCodeContainsFold applies the ContainsFold predicate on the "actor_user_code" field.
func ActorUserCodeContainsFold(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldContainsFold(FieldActorUserCode, v))
}

// ModuleEQ applies the EQ predicate on the "module" field.
func ModuleEQ(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEQ(FieldModule, v))
}

// ModuleNEQ applies the NEQ predicate on the "module" field.
func ModuleNEQ(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldNEQ(FieldModule, v))
}

// ModuleIn applies the In predicate on the "module" field.
func ModuleIn(vs ...string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldIn(FieldModule, vs...))
}

// ModuleNotIn applies the NotIn predicate on the "module" field.
func ModuleNotIn(vs ...string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldNotIn(FieldModule, vs...))
}

// ModuleGT applies the GT predicate on the "module" field.
func ModuleGT(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldGT(FieldModule, v))
}

// ModuleGTE applies the GTE predicate on the "module" field.
func ModuleGTE(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldGTE(FieldModule, v))
}

// ModuleLT applies the LT predicate on the "module" field.
func ModuleLT(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldLT(FieldModule, v))
}

// ModuleLTE applies the LTE predicate on the "module" field.
func ModuleLTE(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldLTE(FieldModule, v))
}

// ModuleContains applies the Contains predicate on the "module" field.
func ModuleContains(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldContains(FieldModule, v))
}

// ModuleHasPrefix applies the HasPrefix predicate on the "module" field.
func ModuleHasPrefix(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldHasPrefix(FieldModule, v))
}

// ModuleHasSuffix applies the HasSuffix predicate on the "module" field.
func ModuleHasSuffix(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldHasSuffix(FieldModule, v))
}

// ModuleEqualFold applies the EqualFold predicate on the "module" field.
func ModuleEqualFold(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEqualFold(FieldModule, v))
}

// ModuleContainsFold applies the ContainsFold predicate on the "module" field.
func ModuleContainsFold(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldContainsFold(FieldModule, v))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldHasSuffix(FieldAction, v))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldContainsFold(FieldAction, v))
}

// MethodEQ applies the EQ predicate on the "method" field.
func MethodEQ(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEQ(FieldMethod, v))
}

// MethodNEQ applies the NEQ predicate on the "method" field.
func MethodNEQ(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldNEQ(FieldMethod, v))
}

// MethodIn applies the In predicate on the "method" field.
func MethodIn(vs ...string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldIn(FieldMethod, vs...))
}

// MethodNotIn applies the NotIn predicate on the "method" field.
func MethodNotIn(vs ...string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldNotIn(FieldMethod, vs...))
}

// MethodGT applies the GT predicate on the "method" field.
func MethodGT(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldGT(FieldMethod, v))
}

// MethodGTE applies the GTE predicate on the "method" field.
func MethodGTE(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldGTE(FieldMethod, v))
}

// MethodLT applies the LT predicate on the "method" field.
func MethodLT(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldLT(FieldMethod, v))
}

// MethodLTE applies the LTE predicate on the "method" field.
func MethodLTE(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldLTE(FieldMethod, v))
}

// MethodContains applies the Contains predicate on the "method" field.
func MethodContains(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldContains(FieldMethod, v))
}

// MethodHasPrefix applies the HasPrefix predicate on the "method" field.
func MethodHasPrefix(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldHasPrefix(FieldMethod, v))
}

// MethodHasSuffix applies the HasSuffix predicate on the "method" field.
func MethodHasSuffix(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldHasSuffix(FieldMethod, v))
}

// MethodEqualFold applies the EqualFold predicate on the "method" field.
func MethodEqualFold(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEqualFold(FieldMethod, v))
}

// MethodContainsFold applies the ContainsFold predicate on the "method" field.
func MethodContainsFold(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldContainsFold(FieldMethod, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldHasSuffix(FieldPath, v))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldContainsFold(FieldPath, v))
}

// NormalizedPathEQ applies the EQ predicate on the "normalized_path" field.
func NormalizedPathEQ(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEQ(FieldNormalizedPath, v))
}

// NormalizedPathNEQ applies the NEQ predicate on the "normalized_path" field.
func NormalizedPathNEQ(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldNEQ(FieldNormalizedPath, v))
}

// NormalizedPathIn applies the In predicate on the "normalized_path" field.
func NormalizedPathIn(vs ...string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldIn(FieldNormalizedPath, vs...))
}

// NormalizedPathNotIn applies the NotIn predicate on the "normalized_path" field.
func NormalizedPathNotIn(vs ...string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldNotIn(FieldNormalizedPath, vs...))
}

// NormalizedPathGT applies the GT predicate on the "normalized_path" field.
func NormalizedPathGT(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldGT(FieldNormalizedPath, v))
}

// NormalizedPathGTE applies the GTE predicate on the "normalized_path" field.
func NormalizedPathGTE(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldGTE(FieldNormalizedPath, v))
}

// NormalizedPathLT applies the LT predicate on the "normalized_path" field.
func NormalizedPathLT(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldLT(FieldNormalizedPath, v))
}

// NormalizedPathLTE applies the LTE predicate on the "normalized_path" field.
func NormalizedPathLTE(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldLTE(FieldNormalizedPath, v))
}

// NormalizedPathContains applies the Contains predicate on the "normalized_path" field.
func NormalizedPathContains(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldContains(FieldNormalizedPath, v))
}

// NormalizedPathHasPrefix applies the HasPrefix predicate on the "normalized_path" field.
func NormalizedPathHasPrefix(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldHasPrefix(FieldNormalizedPath, v))
}

// NormalizedPathHasSuffix applies the HasSuffix predicate on the "normalized_path" field.
func NormalizedPathHasSuffix(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldHasSuffix(FieldNormalizedPath, v))
}

// NormalizedPathEqualFold applies the EqualFold predicate on the "normalized_path" field.
func NormalizedPathEqualFold(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEqualFold(FieldNormalizedPath, v))
}

// NormalizedPathContainsFold applies the ContainsFold predicate on the "normalized_path" field.
func NormalizedPathContainsFold(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldContainsFold(FieldNormalizedPath, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v int) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v int) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...int) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...int) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v int) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v int) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v int) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v int) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldLTE(FieldStatus, v))
}

// TargetIDEQ applies the EQ predicate on the "target_id" field.
func TargetIDEQ(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEQ(FieldTargetID, v))
}

// TargetIDNEQ applies the NEQ predicate on the "target_id" field.
func TargetIDNEQ(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldNEQ(FieldTargetID, v))
}

// TargetIDIn applies the In predicate on the "target_id" field.
func TargetIDIn(vs ...string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldIn(FieldTargetID, vs...))
}

// TargetIDNotIn applies the NotIn predicate on the "target_id" field.
func TargetIDNotIn(vs ...string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldNotIn(FieldTargetID, vs...))
}

// TargetIDGT applies the GT predicate on the "target_id" field.
func TargetIDGT(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldGT(FieldTargetID, v))
}

// TargetIDGTE applies the GTE predicate on the "target_id" field.
func TargetIDGTE(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldGTE(FieldTargetID, v))
}

// TargetIDLT applies the LT predicate on the "target_id" field.
func TargetIDLT(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldLT(FieldTargetID, v))
}

// TargetIDLTE applies the LTE predicate on the "target_id" field.
func TargetIDLTE(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldLTE(FieldTargetID, v))
}

// TargetIDContains applies the Contains predicate on the "target_id" field.
func TargetIDContains(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldContains(FieldTargetID, v))
}

// TargetIDHasPrefix applies the HasPrefix predicate on the "target_id" field.
func TargetIDHasPrefix(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldHasPrefix(FieldTargetID, v))
}

// TargetIDHasSuffix applies the HasSuffix predicate on the "target_id" field.
func TargetIDHasSuffix(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldHasSuffix(FieldTargetID, v))
}

// TargetIDEqualFold applies the EqualFold predicate on the "target_id" field.
func TargetIDEqualFold(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEqualFold(FieldTargetID, v))
}

// TargetIDContainsFold applies the ContainsFold predicate on the "target_id" field.
func TargetIDContainsFold(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldContainsFold(FieldTargetID, v))
}

// IPEQ applies the EQ predicate on the "ip" field.
func IPEQ(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEQ(FieldIP, v))
}

// IPNEQ applies the NEQ predicate on the "ip" field.
func IPNEQ(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldNEQ(FieldIP, v))
}

// IPIn applies the In predicate on the "ip" field.
func IPIn(vs ...string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldIn(FieldIP, vs...))
}

// IPNotIn applies the NotIn predicate on the "ip" field.
func IPNotIn(vs ...string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldNotIn(FieldIP, vs...))
}

// IPGT applies the GT predicate on the "ip" field.
func IPGT(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldGT(FieldIP, v))
}

// IPGTE applies the GTE predicate on the "ip" field.
func IPGTE(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldGTE(FieldIP, v))
}

// IPLT applies the LT predicate on the "ip" field.
func IPLT(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldLT(FieldIP, v))
}

// IPLTE applies the LTE predicate on the "ip" field.
func IPLTE(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldLTE(FieldIP, v))
}

// IPContains applies the Contains predicate on the "ip" field.
func IPContains(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldContains(FieldIP, v))
}

// IPHasPrefix applies the HasPrefix predicate on the "ip" field.
func IPHasPrefix(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldHasPrefix(FieldIP, v))
}

// IPHasSuffix applies the HasSuffix predicate on the "ip" field.
func IPHasSuffix(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldHasSuffix(FieldIP, v))
}

// IPEqualFold applies the EqualFold predicate on the "ip" field.
func IPEqualFold(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEqualFold(FieldIP, v))
}

// IPContainsFold applies the ContainsFold predicate on the "ip" field.
func IPContainsFold(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldContainsFold(FieldIP, v))
}

// UserAgentEQ applies the EQ predicate on the "user_agent" field.
func UserAgentEQ(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "user_agent" field.
func UserAgentNEQ(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "user_agent" field.
func UserAgentIn(vs ...string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "user_agent" field.
func UserAgentNotIn(vs ...string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "user_agent" field.
func UserAgentGT(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "user_agent" field.
func UserAgentGTE(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "user_agent" field.
func UserAgentLT(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "user_agent" field.
func UserAgentLTE(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "user_agent" field.
func UserAgentContains(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "user_agent" field.
func UserAgentHasPrefix(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "user_agent" field.
func UserAgentHasSuffix(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentEqualFold applies the EqualFold predicate on the "user_agent" field.
func UserAgentEqualFold(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "user_agent" field.
func UserAgentContainsFold(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldContainsFold(FieldUserAgent, v))
}

// SummaryEQ applies the EQ predicate on the "summary" field.
func SummaryEQ(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEQ(FieldSummary, v))
}

// SummaryNEQ applies the NEQ predicate on the "summary" field.
func SummaryNEQ(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldNEQ(FieldSummary, v))
}

// SummaryIn applies the In predicate on the "summary" field.
func SummaryIn(vs ...string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldIn(FieldSummary, vs...))
}

// SummaryNotIn applies the NotIn predicate on the "summary" field.
func SummaryNotIn(vs ...string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldNotIn(FieldSummary, vs...))
}

// SummaryGT applies the GT predicate on the "summary" field.
func SummaryGT(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldGT(FieldSummary, v))
}

// SummaryGTE applies the GTE predicate on the "summary" field.
func SummaryGTE(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldGTE(FieldSummary, v))
}

// SummaryLT applies the LT predicate on the "summary" field.
func SummaryLT(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldLT(FieldSummary, v))
}

// SummaryLTE applies the LTE predicate on the "summary" field.
func SummaryLTE(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldLTE(FieldSummary, v))
}

// SummaryContains applies the Contains predicate on the "summary" field.
func SummaryContains(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldContains(FieldSummary, v))
}

// SummaryHasPrefix applies the HasPrefix predicate on the "summary" field.
func SummaryHasPrefix(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldHasPrefix(FieldSummary, v))
}

// SummaryHasSuffix applies the HasSuffix predicate on the "summary" field.
func SummaryHasSuffix(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldHasSuffix(FieldSummary, v))
}

// SummaryEqualFold applies the EqualFold predicate on the "summary" field.
func SummaryEqualFold(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldEqualFold(FieldSummary, v))
}

// SummaryContainsFold applies the ContainsFold predicate on the "summary" field.
func SummaryContainsFold(v string) predicate.OperationLog {
	return predicate.OperationLog(sql.FieldContainsFold(FieldSummary, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OperationLog) predicate.OperationLog {
	return predicate.OperationLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OperationLog) predicate.OperationLog {
	return predicate.OperationLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OperationLog) predicate.OperationLog {
	return predicate.OperationLog(sql.NotPredicates(p))
}
