// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AssignIAMUserRoleReply struct {
}

type AssignIAMUserRoleReq struct {
	UserCode string `json:"user_code"`
	RoleCode string `json:"role_code"`
}

type CategorySpec struct {
	Id         uint64 `json:"id,string"`
	CategoryId uint64 `json:"category_id,string"`
	SpecItemId uint64 `json:"spec_item_id,optional,string"`
	SpecType   string `json:"spec_type"`
	SpecValue  string `json:"spec_value"`
	PriceDelta int64  `json:"price_delta"`
	Sort       uint32 `json:"sort,optional"` // 排序（不传默认0）
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

type CreateCategorySpecReply struct {
}

type CreateCategorySpecReq struct {
	CategoryId uint64 `json:"category_id,string"`
	SpecItemId uint64 `json:"spec_item_id,optional,string"`
	SpecType   string `json:"spec_type"`
	SpecValue  string `json:"spec_value"`
	PriceDelta int64  `json:"price_delta,optional"`
	Sort       uint32 `json:"sort,optional"`
}

type CreateIAMRoleReply struct {
	Id uint64 `json:"id"`
}

type CreateIAMRoleReq struct {
	RoleCode string `json:"role_code"`
	RoleName string `json:"role_name,optional"`
}

type CreateIAMUserReply struct {
	Id uint64 `json:"id"`
}

type CreateIAMUserReq struct {
	UserCode    string `json:"user_code"`
	DisplayName string `json:"display_name,optional"`
}

type CreateMenuCategoryReply struct {
}

type CreateMenuCategoryReq struct {
	Name        string `json:"name"`
	Description string `json:"description,optional"`
	Sort        uint32 `json:"sort,optional"`
}

type CreateMenuReply struct {
}

type CreateMenuReq struct {
	Name        string     `json:"name"`
	Description string     `json:"description,optional"`
	Image       string     `json:"image,optional"`
	Price       int64      `json:"price"` // 以分为单位，避免前端浮点数问题，展示/100
	CategoryId  uint64     `json:"category_id,string"`
	Specs       []MenuSpec `json:"specs,optional"`
}

type CreateOrderItemReq struct {
	MenuName  string `json:"menu_name"`
	Quantity  int    `json:"quantity"`
	UnitPrice int64  `json:"unit_price"`
	SpecInfo  string `json:"spec_info,optional"`
}

type CreateOrderReply struct {
	Order Order `json:"order"`
}

type CreateOrderReq struct {
	OrderType   string               `json:"order_type"`               // dine_in | takeaway
	TableId     uint64               `json:"table_id,optional,string"` // 堂食必填
	Items       []CreateOrderItemReq `json:"items"`
	TotalAmount int64                `json:"total_amount"`
	Remark      string               `json:"remark,optional"`
}

type CreateSpecGroupReply struct {
}

type CreateSpecGroupReq struct {
	Name string `json:"name"`
	Sort uint32 `json:"sort,optional"`
}

type CreateSpecItemReply struct {
}

type CreateSpecItemReq struct {
	SpecGroupId  uint64 `json:"spec_group_id,string"`
	Name         string `json:"name"`
	DefaultPrice int64  `json:"default_price,optional"`
}

type CreateTableCategoryReply struct {
}

type CreateTableCategoryReq struct {
	Name        string `json:"name"`
	Description string `json:"description,optional"`
}

type CreateTableReply struct {
}

type CreateTableReq struct {
	Code       string `json:"code"`
	Status     string `json:"status"`
	Capacity   uint32 `json:"capacity,optional"`
	CategoryId uint64 `json:"category_id,string"`
	QrCode     string `json:"qr_code,optional"`
}

type DeleteCategorySpecReply struct {
}

type DeleteCategorySpecReq struct {
	Id uint64 `path:"id"`
}

type DeleteIAMRoleReply struct {
}

type DeleteIAMRoleReq struct {
	Id uint64 `path:"id"`
}

type DeleteIAMUserReply struct {
}

type DeleteIAMUserReq struct {
	Id uint64 `path:"id"`
}

type DeleteMenuCategoryReply struct {
}

type DeleteMenuCategoryReq struct {
	Id uint64 `path:"id"`
}

type DeleteMenuReply struct {
}

type DeleteMenuReq struct {
	Id uint64 `path:"id"`
}

type DeleteSpecGroupReply struct {
}

type DeleteSpecGroupReq struct {
	Id uint64 `path:"id"`
}

type DeleteSpecItemReply struct {
}

type DeleteSpecItemReq struct {
	Id uint64 `path:"id"`
}

type DeleteTableCategoryReply struct {
}

type DeleteTableCategoryReq struct {
	Id uint64 `path:"id"`
}

type DeleteTableReply struct {
}

type DeleteTableReq struct {
	Id uint64 `path:"id"`
}

type GetCategorySpecReply struct {
	Spec CategorySpec `json:"spec"`
}

type GetCategorySpecReq struct {
	Id uint64 `path:"id"`
}

type GetIAMPermissionReply struct {
	Permission PermissionItem `json:"permission"`
}

type GetIAMPermissionReq struct {
	Id uint64 `path:"id"`
}

type GetIAMRoleReply struct {
	Role IAMRoleItem `json:"role"`
}

type GetIAMRoleReq struct {
	Id uint64 `path:"id"`
}

type GetIAMUserReply struct {
	User IAMUserItem `json:"user"`
}

type GetIAMUserReq struct {
	Id uint64 `path:"id"`
}

type GetMenuCategoryReply struct {
	Category MenuCategory `json:"category"`
}

type GetMenuCategoryReq struct {
	Id uint64 `path:"id"`
}

type GetMenuReply struct {
	Menu Menu `json:"menu"`
}

type GetMenuReq struct {
	Id uint64 `path:"id"`
}

type GetOrderReply struct {
	Order Order `json:"order"`
}

type GetOrderReq struct {
	Id uint64 `path:"id"`
}

type GetRolePermissionReply struct {
	RolePermission RolePermission `json:"role_permission"`
}

type GetRolePermissionReq struct {
	Role string `path:"role"`
}

type GetSpecGroupReply struct {
	Group SpecGroup `json:"group"`
}

type GetSpecGroupReq struct {
	Id uint64 `path:"id"`
}

type GetSpecItemReply struct {
	Item SpecItem `json:"item"`
}

type GetSpecItemReq struct {
	Id uint64 `path:"id"`
}

type GetTableCategoryReply struct {
	TableCategory TableCategory `json:"category"`
}

type GetTableCategoryReq struct {
	Id uint64 `path:"id"`
}

type GetTableReply struct {
	Table Table `json:"table"`
}

type GetTableReq struct {
	Id uint64 `path:"id"`
}

type IAMRoleItem struct {
	Id       uint64 `json:"id"`
	RoleCode string `json:"role_code"`
	RoleName string `json:"role_name"`
}

type IAMUserItem struct {
	Id          uint64   `json:"id"`
	UserCode    string   `json:"user_code"`
	DisplayName string   `json:"display_name"`
	Roles       []string `json:"roles"`
}

type ListCategorySpecReply struct {
	Specs []CategorySpec `json:"specs"`
	Total int64          `json:"total"`
}

type ListCategorySpecReq struct {
	PageInfo
	CategoryId uint64 `json:"category_id,optional,string" form:"category_id,optional"`
	SpecType   string `json:"spec_type,optional" form:"spec_type,optional"`
}

type ListIAMPermissionsReply struct {
	Permissions []PermissionItem `json:"permissions"`
	Total       int64            `json:"total"`
}

type ListIAMPermissionsReq struct {
	PageInfo
	Keyword string `json:"keyword,optional" form:"keyword,optional"` // 可选：按 code/description 模糊筛
}

type ListIAMRolesReply struct {
	Roles []IAMRoleItem `json:"roles"`
	Total int64         `json:"total"`
}

type ListIAMRolesReq struct {
	PageInfo
	Keyword string `json:"keyword,optional" form:"keyword,optional"`
}

type ListIAMUsersReply struct {
	Users []IAMUserItem `json:"users"`
	Total int64         `json:"total"`
}

type ListIAMUsersReq struct {
	PageInfo
	Keyword string `json:"keyword,optional" form:"keyword,optional"` // 可选：user_code / display_name
}

type ListMenuCategoryReply struct {
	Categories []MenuCategory `json:"categories"`
	Total      int64          `json:"total"`
}

type ListMenuCategoryReq struct {
	PageInfo
	Name string `json:"name,optional" form:"name,optional"`
}

type ListMenuReply struct {
	Menus []Menu `json:"menus"`
	Total int64  `json:"total"`
}

type ListMenuReq struct {
	PageInfo
	Name       string `json:"name,optional" form:"name,optional"`
	CategoryId uint64 `json:"category_id,optional,string" form:"category_id,optional"` // 按分类id筛选
	Category   string `json:"category,optional" form:"category,optional"`              // 按分类名字筛选
}

type ListOrderReply struct {
	Orders []Order `json:"orders"`
	Total  int64   `json:"total"`
}

type ListOrderReq struct {
	PageInfo
	Status    string `json:"status,optional" form:"status,optional"`
	OrderType string `json:"order_type,optional" form:"order_type,optional"`    // dine_in | takeaway
	TableId   uint64 `json:"table_id,optional,string" form:"table_id,optional"` // 按餐桌筛选
}

type ListRolePermissionReply struct {
	Roles []RolePermission `json:"roles"`
}

type ListSpecGroupReply struct {
	Groups []SpecGroup `json:"groups"`
	Total  int64       `json:"total"`
}

type ListSpecGroupReq struct {
	PageInfo
	Name string `json:"name,optional" form:"name,optional"`
}

type ListSpecItemReply struct {
	Items []SpecItem `json:"items"`
	Total int64      `json:"total"`
}

type ListSpecItemReq struct {
	PageInfo
	SpecGroupId uint64 `json:"spec_group_id,optional,string" form:"spec_group_id,optional"`
	Name        string `json:"name,optional" form:"name,optional"`
}

type ListTableCategoryReply struct {
	Categories []TableCategory `json:"categories"`
	Total      int64           `json:"total"`
}

type ListTableCategoryReq struct {
	PageInfo
	Name string `json:"name,optional" form:"name,optional"`
}

type ListTableReply struct {
	Tables []Table `json:"tables"`
	Total  int64   `json:"total"`
}

type ListTableReq struct {
	Current    int64  `json:"current,optional" form:"current,optional"`
	PageSize   int64  `json:"pageSize,optional" form:"pageSize,optional"`
	Code       string `json:"code,optional" form:"code,optional"`
	Status     string `json:"status,optional" form:"status,optional"`
	CategoryId uint64 `json:"category_id,optional,string" form:"category_id,optional"` // 按分类id筛选
	Category   string `json:"category,optional" form:"category,optional"`              // 按分类名字筛选
}

type ListWorkbenchOrderReply struct {
	Orders []Order `json:"orders"`
	Total  int64   `json:"total"`
}

type ListWorkbenchOrderReq struct {
	Current  int64  `json:"current,optional" form:"current,optional"`
	PageSize int64  `json:"pageSize,optional" form:"pageSize,optional"`
	Status   string `json:"status,optional" form:"status,optional"` // 不传则默认查 created,paid,preparing
}

type LoginReply struct {
	AccessToken string `json:"access_token"`
	Expire      int64  `json:"expire"` // 过期时间戳（秒）
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Menu struct {
	Id          uint64     `json:"id,string"`            // 菜单id
	Name        string     `json:"name"`                 // 菜单名称
	Description string     `json:"description,optional"` // 菜单描述
	Image       string     `json:"image,optional"`       // 菜单图片
	Price       int64      `json:"price"`                // 菜单价格（分）
	CategoryId  uint64     `json:"category_id,string"`   // 菜单分类id
	Specs       []MenuSpec `json:"specs,optional"`       // 规格列表
	CreatedAt   string     `json:"created_at"`           // 创建时间，RFC3339（UTC），列表与详情均返回
	UpdatedAt   string     `json:"updated_at"`           // 更新时间，RFC3339（UTC），列表与详情均返回
}

type MenuCategory struct {
	Id          uint64 `json:"id,string"`            // 分类id
	Name        string `json:"name"`                 // 分类名称
	Description string `json:"description,optional"` // 描述
	Sort        uint32 `json:"sort,optional"`        // 排序，越小越靠前
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type MenuSpec struct {
	SpecItemId     uint64 `json:"spec_item_id,optional,string"`     // 规格项id
	CategorySpecId uint64 `json:"category_spec_id,optional,string"` // 分类规格项id
	Source         string `json:"source,optional"`                  // category=分类规格 library=基础规格 custom=菜单自定义
	SpecType       string `json:"spec_type,optional"`               // 规格类型，如辣度
	SpecValue      string `json:"spec_value,optional"`              // 规格值，如微辣
	PriceDelta     int64  `json:"price_delta"`                      // 加价
	Sort           uint32 `json:"sort,optional"`                    // 排序（不传默认0）
}

type Order struct {
	Id            uint64      `json:"id,string"`                // 订单id
	OrderNo       string      `json:"order_no"`                 // 订单号
	OrderType     string      `json:"order_type"`               // dine_in=堂食 takeaway=打包外带
	Status        string      `json:"status"`                   // created/paid/preparing/completed/cancelled
	TotalAmount   int64       `json:"total_amount"`             // 总金额
	TableId       uint64      `json:"table_id,optional,string"` // 堂食时关联餐桌id
	TableCode     string      `json:"table_code,optional"`      // 桌号（堂食时显示，外带为空）
	TableCategory string      `json:"table_category,optional"`  // 餐桌类别（如大厅、包间）
	Remark        string      `json:"remark,optional"`          // 备注
	Items         []OrderItem `json:"items,optional"`           // 订单明细
	CreatedAt     string      `json:"created_at"`               // 创建时间
	UpdatedAt     string      `json:"updated_at"`               // 更新时间
}

type OrderItem struct {
	MenuName  string `json:"menu_name"`          // 菜品名称快照
	Quantity  int    `json:"quantity"`           // 数量
	UnitPrice int64  `json:"unit_price"`         // 单价
	Amount    int64  `json:"amount"`             // 小计
	SpecInfo  string `json:"spec_info,optional"` // 规格描述快照
}

type PageInfo struct {
	Current  int64 `json:"current,optional" form:"current,optional"`
	PageSize int64 `json:"pageSize,optional" form:"pageSize,optional"`
}

type PermissionItem struct {
	Id          uint64 `json:"id"`
	Code        string `json:"code"`
	Description string `json:"description"`
}

type RemoveIAMUserRoleReply struct {
}

type RemoveIAMUserRoleReq struct {
	UserCode string `json:"user_code,optional" form:"user_code"`
	RoleCode string `json:"role_code,optional" form:"role_code"`
}

type ResetRolePermissionsReply struct {
}

type ResetRolePermissionsReq struct {
	Role string `json:"role,optional"`
}

type RolePermission struct {
	Role        string   `json:"role"`
	Permissions []string `json:"permissions"`
}

type SpecGroup struct {
	Id        uint64 `json:"id,string"`
	Name      string `json:"name"`
	Sort      uint32 `json:"sort,optional"` // 排序（不传默认0）
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type SpecItem struct {
	Id           uint64 `json:"id,string"`
	SpecGroupId  uint64 `json:"spec_group_id,string"`
	Name         string `json:"name"`
	DefaultPrice int64  `json:"default_price"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type SyncCasbinPoliciesReply struct {
}

type SyncCasbinPoliciesReq struct {
}

type Table struct {
	Id         uint64 `json:"id,string"`          // 餐桌id
	Code       string `json:"code"`               // 桌号
	Status     string `json:"status"`             // idle=空闲 using=使用中 reserved=预留 cleaning=清洁中
	Capacity   uint32 `json:"capacity,optional"`  // 可坐人数
	CategoryId uint64 `json:"category_id,string"` // 餐桌分类id
	QrCode     string `json:"qr_code,optional"`   // 二维码
	CreatedAt  string `json:"created_at"`         // 创建时间
	UpdatedAt  string `json:"updated_at"`         // 更新时间
}

type TableCategory struct {
	Id          uint64 `json:"id,string"`            // 分类id
	Name        string `json:"name"`                 // 分类名称
	Description string `json:"description,optional"` // 描述
}

type UpdateCategorySpecReply struct {
}

type UpdateCategorySpecReq struct {
	Id         uint64 `path:"id"`
	CategoryId uint64 `json:"category_id,string"`
	SpecItemId uint64 `json:"spec_item_id,optional,string"`
	SpecType   string `json:"spec_type"`
	SpecValue  string `json:"spec_value"`
	PriceDelta int64  `json:"price_delta,optional"`
	Sort       uint32 `json:"sort,optional"`
}

type UpdateIAMRoleReply struct {
}

type UpdateIAMRoleReq struct {
	Id       uint64 `path:"id"`
	RoleName string `json:"role_name"`
}

type UpdateIAMUserReply struct {
}

type UpdateIAMUserReq struct {
	Id          uint64 `path:"id"`
	DisplayName string `json:"display_name"`
}

type UpdateMenuCategoryReply struct {
}

type UpdateMenuCategoryReq struct {
	Id          uint64  `path:"id"`
	Name        string  `json:"name,optional"`
	Description *string `json:"description,omitempty"`
	Sort        uint32  `json:"sort,optional"`
}

type UpdateMenuReply struct {
}

type UpdateMenuReq struct {
	Id          uint64     `path:"id"`
	Name        string     `json:"name"`
	Description string     `json:"description,optional"`
	Image       string     `json:"image,optional"`
	Price       int64      `json:"price,optional"`
	CategoryId  uint64     `json:"category_id,optional,string"`
	Specs       []MenuSpec `json:"specs,optional"`
}

type UpdateOrderStatusReply struct {
}

type UpdateOrderStatusReq struct {
	Id     uint64 `path:"id"`
	Status string `json:"status"` // paid/preparing/completed/cancelled
}

type UpdateRolePermissionsReply struct {
}

type UpdateRolePermissionsReq struct {
	Role        string   `path:"role"`
	Permissions []string `json:"permissions"`
}

type UpdateSpecGroupReply struct {
}

type UpdateSpecGroupReq struct {
	Id   uint64 `path:"id"`
	Name string `json:"name"`
	Sort uint32 `json:"sort,optional"`
}

type UpdateSpecItemReply struct {
}

type UpdateSpecItemReq struct {
	Id           uint64 `path:"id"`
	SpecGroupId  uint64 `json:"spec_group_id,string"`
	Name         string `json:"name"`
	DefaultPrice int64  `json:"default_price,optional"`
}

type UpdateTableCategoryInput struct {
	Name        string `json:"name"`
	Description string `json:"description,optional"`
}

type UpdateTableCategoryReply struct {
}

type UpdateTableCategoryReq struct {
	Id            uint64                   `path:"id"`
	TableCategory UpdateTableCategoryInput `json:"category"`
}

type UpdateTableReply struct {
}

type UpdateTableReq struct {
	Id         uint64 `path:"id"`
	Code       string `json:"code"`
	Status     string `json:"status"`
	Capacity   uint32 `json:"capacity,optional"`
	CategoryId uint64 `json:"category_id,string"`
	QrCode     string `json:"qr_code,optional"`
}
