// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CategorySpec is the predicate function for categoryspec builders.
type CategorySpec func(*sql.Selector)

// IAMPermission is the predicate function for iampermission builders.
type IAMPermission func(*sql.Selector)

// IAMRole is the predicate function for iamrole builders.
type IAMRole func(*sql.Selector)

// IAMUser is the predicate function for iamuser builders.
type IAMUser func(*sql.Selector)

// Menu is the predicate function for menu builders.
type Menu func(*sql.Selector)

// MenuCategory is the predicate function for menucategory builders.
type MenuCategory func(*sql.Selector)

// MenuSpec is the predicate function for menuspec builders.
type MenuSpec func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// OrderItem is the predicate function for orderitem builders.
type OrderItem func(*sql.Selector)

// SpecGroup is the predicate function for specgroup builders.
type SpecGroup func(*sql.Selector)

// SpecItem is the predicate function for specitem builders.
type SpecItem func(*sql.Selector)

// Table is the predicate function for table builders.
type Table func(*sql.Selector)

// TableCategory is the predicate function for tablecategory builders.
type TableCategory func(*sql.Selector)
