// Code generated by ent, DO NOT EDIT.

package iamuser

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/solikewind/happyeat/dal/model/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeleteTs applies equality check predicate on the "delete_ts" field. It's identical to DeleteTsEQ.
func DeleteTs(v int64) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldEQ(FieldDeleteTs, v))
}

// UserCode applies equality check predicate on the "user_code" field. It's identical to UserCodeEQ.
func UserCode(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldEQ(FieldUserCode, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldEQ(FieldDisplayName, v))
}

// Phone applies equality check predicate on the "phone" field. It's identical to PhoneEQ.
func Phone(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldEQ(FieldPhone, v))
}

// PasswordHash applies equality check predicate on the "password_hash" field. It's identical to PasswordHashEQ.
func PasswordHash(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldEQ(FieldPasswordHash, v))
}

// AvatarObjectID applies equality check predicate on the "avatar_object_id" field. It's identical to AvatarObjectIDEQ.
func AvatarObjectID(v uint64) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldEQ(FieldAvatarObjectID, v))
}

// AvatarURL applies equality check predicate on the "avatar_url" field. It's identical to AvatarURLEQ.
func AvatarURL(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldEQ(FieldAvatarURL, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeleteTsEQ applies the EQ predicate on the "delete_ts" field.
func DeleteTsEQ(v int64) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldEQ(FieldDeleteTs, v))
}

// DeleteTsNEQ applies the NEQ predicate on the "delete_ts" field.
func DeleteTsNEQ(v int64) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldNEQ(FieldDeleteTs, v))
}

// DeleteTsIn applies the In predicate on the "delete_ts" field.
func DeleteTsIn(vs ...int64) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldIn(FieldDeleteTs, vs...))
}

// DeleteTsNotIn applies the NotIn predicate on the "delete_ts" field.
func DeleteTsNotIn(vs ...int64) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldNotIn(FieldDeleteTs, vs...))
}

// DeleteTsGT applies the GT predicate on the "delete_ts" field.
func DeleteTsGT(v int64) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldGT(FieldDeleteTs, v))
}

// DeleteTsGTE applies the GTE predicate on the "delete_ts" field.
func DeleteTsGTE(v int64) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldGTE(FieldDeleteTs, v))
}

// DeleteTsLT applies the LT predicate on the "delete_ts" field.
func DeleteTsLT(v int64) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldLT(FieldDeleteTs, v))
}

// DeleteTsLTE applies the LTE predicate on the "delete_ts" field.
func DeleteTsLTE(v int64) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldLTE(FieldDeleteTs, v))
}

// UserCodeEQ applies the EQ predicate on the "user_code" field.
func UserCodeEQ(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldEQ(FieldUserCode, v))
}

// UserCodeNEQ applies the NEQ predicate on the "user_code" field.
func UserCodeNEQ(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldNEQ(FieldUserCode, v))
}

// UserCodeIn applies the In predicate on the "user_code" field.
func UserCodeIn(vs ...string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldIn(FieldUserCode, vs...))
}

// UserCodeNotIn applies the NotIn predicate on the "user_code" field.
func UserCodeNotIn(vs ...string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldNotIn(FieldUserCode, vs...))
}

// UserCodeGT applies the GT predicate on the "user_code" field.
func UserCodeGT(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldGT(FieldUserCode, v))
}

// UserCodeGTE applies the GTE predicate on the "user_code" field.
func UserCodeGTE(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldGTE(FieldUserCode, v))
}

// UserCodeLT applies the LT predicate on the "user_code" field.
func UserCodeLT(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldLT(FieldUserCode, v))
}

// UserCodeLTE applies the LTE predicate on the "user_code" field.
func UserCodeLTE(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldLTE(FieldUserCode, v))
}

// UserCodeContains applies the Contains predicate on the "user_code" field.
func UserCodeContains(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldContains(FieldUserCode, v))
}

// UserCodeHasPrefix applies the HasPrefix predicate on the "user_code" field.
func UserCodeHasPrefix(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldHasPrefix(FieldUserCode, v))
}

// UserCodeHasSuffix applies the HasSuffix predicate on the "user_code" field.
func UserCodeHasSuffix(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldHasSuffix(FieldUserCode, v))
}

// UserCodeEqualFold applies the EqualFold predicate on the "user_code" field.
func UserCodeEqualFold(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldEqualFold(FieldUserCode, v))
}

// UserCodeContainsFold applies the ContainsFold predicate on the "user_code" field.
func UserCodeContainsFold(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldContainsFold(FieldUserCode, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldContainsFold(FieldDisplayName, v))
}

// PhoneEQ applies the EQ predicate on the "phone" field.
func PhoneEQ(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldEQ(FieldPhone, v))
}

// PhoneNEQ applies the NEQ predicate on the "phone" field.
func PhoneNEQ(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldNEQ(FieldPhone, v))
}

// PhoneIn applies the In predicate on the "phone" field.
func PhoneIn(vs ...string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldIn(FieldPhone, vs...))
}

// PhoneNotIn applies the NotIn predicate on the "phone" field.
func PhoneNotIn(vs ...string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldNotIn(FieldPhone, vs...))
}

// PhoneGT applies the GT predicate on the "phone" field.
func PhoneGT(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldGT(FieldPhone, v))
}

// PhoneGTE applies the GTE predicate on the "phone" field.
func PhoneGTE(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldGTE(FieldPhone, v))
}

// PhoneLT applies the LT predicate on the "phone" field.
func PhoneLT(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldLT(FieldPhone, v))
}

// PhoneLTE applies the LTE predicate on the "phone" field.
func PhoneLTE(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldLTE(FieldPhone, v))
}

// PhoneContains applies the Contains predicate on the "phone" field.
func PhoneContains(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldContains(FieldPhone, v))
}

// PhoneHasPrefix applies the HasPrefix predicate on the "phone" field.
func PhoneHasPrefix(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldHasPrefix(FieldPhone, v))
}

// PhoneHasSuffix applies the HasSuffix predicate on the "phone" field.
func PhoneHasSuffix(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldHasSuffix(FieldPhone, v))
}

// PhoneEqualFold applies the EqualFold predicate on the "phone" field.
func PhoneEqualFold(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldEqualFold(FieldPhone, v))
}

// PhoneContainsFold applies the ContainsFold predicate on the "phone" field.
func PhoneContainsFold(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldContainsFold(FieldPhone, v))
}

// PasswordHashEQ applies the EQ predicate on the "password_hash" field.
func PasswordHashEQ(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldEQ(FieldPasswordHash, v))
}

// PasswordHashNEQ applies the NEQ predicate on the "password_hash" field.
func PasswordHashNEQ(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldNEQ(FieldPasswordHash, v))
}

// PasswordHashIn applies the In predicate on the "password_hash" field.
func PasswordHashIn(vs ...string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldIn(FieldPasswordHash, vs...))
}

// PasswordHashNotIn applies the NotIn predicate on the "password_hash" field.
func PasswordHashNotIn(vs ...string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldNotIn(FieldPasswordHash, vs...))
}

// PasswordHashGT applies the GT predicate on the "password_hash" field.
func PasswordHashGT(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldGT(FieldPasswordHash, v))
}

// PasswordHashGTE applies the GTE predicate on the "password_hash" field.
func PasswordHashGTE(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldGTE(FieldPasswordHash, v))
}

// PasswordHashLT applies the LT predicate on the "password_hash" field.
func PasswordHashLT(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldLT(FieldPasswordHash, v))
}

// PasswordHashLTE applies the LTE predicate on the "password_hash" field.
func PasswordHashLTE(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldLTE(FieldPasswordHash, v))
}

// PasswordHashContains applies the Contains predicate on the "password_hash" field.
func PasswordHashContains(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldContains(FieldPasswordHash, v))
}

// PasswordHashHasPrefix applies the HasPrefix predicate on the "password_hash" field.
func PasswordHashHasPrefix(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldHasPrefix(FieldPasswordHash, v))
}

// PasswordHashHasSuffix applies the HasSuffix predicate on the "password_hash" field.
func PasswordHashHasSuffix(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldHasSuffix(FieldPasswordHash, v))
}

// PasswordHashEqualFold applies the EqualFold predicate on the "password_hash" field.
func PasswordHashEqualFold(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldEqualFold(FieldPasswordHash, v))
}

// PasswordHashContainsFold applies the ContainsFold predicate on the "password_hash" field.
func PasswordHashContainsFold(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldContainsFold(FieldPasswordHash, v))
}

// AvatarObjectIDEQ applies the EQ predicate on the "avatar_object_id" field.
func AvatarObjectIDEQ(v uint64) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldEQ(FieldAvatarObjectID, v))
}

// AvatarObjectIDNEQ applies the NEQ predicate on the "avatar_object_id" field.
func AvatarObjectIDNEQ(v uint64) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldNEQ(FieldAvatarObjectID, v))
}

// AvatarObjectIDIn applies the In predicate on the "avatar_object_id" field.
func AvatarObjectIDIn(vs ...uint64) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldIn(FieldAvatarObjectID, vs...))
}

// AvatarObjectIDNotIn applies the NotIn predicate on the "avatar_object_id" field.
func AvatarObjectIDNotIn(vs ...uint64) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldNotIn(FieldAvatarObjectID, vs...))
}

// AvatarObjectIDGT applies the GT predicate on the "avatar_object_id" field.
func AvatarObjectIDGT(v uint64) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldGT(FieldAvatarObjectID, v))
}

// AvatarObjectIDGTE applies the GTE predicate on the "avatar_object_id" field.
func AvatarObjectIDGTE(v uint64) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldGTE(FieldAvatarObjectID, v))
}

// AvatarObjectIDLT applies the LT predicate on the "avatar_object_id" field.
func AvatarObjectIDLT(v uint64) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldLT(FieldAvatarObjectID, v))
}

// AvatarObjectIDLTE applies the LTE predicate on the "avatar_object_id" field.
func AvatarObjectIDLTE(v uint64) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldLTE(FieldAvatarObjectID, v))
}

// AvatarURLEQ applies the EQ predicate on the "avatar_url" field.
func AvatarURLEQ(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldEQ(FieldAvatarURL, v))
}

// AvatarURLNEQ applies the NEQ predicate on the "avatar_url" field.
func AvatarURLNEQ(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldNEQ(FieldAvatarURL, v))
}

// AvatarURLIn applies the In predicate on the "avatar_url" field.
func AvatarURLIn(vs ...string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldIn(FieldAvatarURL, vs...))
}

// AvatarURLNotIn applies the NotIn predicate on the "avatar_url" field.
func AvatarURLNotIn(vs ...string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldNotIn(FieldAvatarURL, vs...))
}

// AvatarURLGT applies the GT predicate on the "avatar_url" field.
func AvatarURLGT(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldGT(FieldAvatarURL, v))
}

// AvatarURLGTE applies the GTE predicate on the "avatar_url" field.
func AvatarURLGTE(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldGTE(FieldAvatarURL, v))
}

// AvatarURLLT applies the LT predicate on the "avatar_url" field.
func AvatarURLLT(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldLT(FieldAvatarURL, v))
}

// AvatarURLLTE applies the LTE predicate on the "avatar_url" field.
func AvatarURLLTE(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldLTE(FieldAvatarURL, v))
}

// AvatarURLContains applies the Contains predicate on the "avatar_url" field.
func AvatarURLContains(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldContains(FieldAvatarURL, v))
}

// AvatarURLHasPrefix applies the HasPrefix predicate on the "avatar_url" field.
func AvatarURLHasPrefix(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldHasPrefix(FieldAvatarURL, v))
}

// AvatarURLHasSuffix applies the HasSuffix predicate on the "avatar_url" field.
func AvatarURLHasSuffix(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldHasSuffix(FieldAvatarURL, v))
}

// AvatarURLEqualFold applies the EqualFold predicate on the "avatar_url" field.
func AvatarURLEqualFold(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldEqualFold(FieldAvatarURL, v))
}

// AvatarURLContainsFold applies the ContainsFold predicate on the "avatar_url" field.
func AvatarURLContainsFold(v string) predicate.IAMUser {
	return predicate.IAMUser(sql.FieldContainsFold(FieldAvatarURL, v))
}

// HasRoles applies the HasEdge predicate on the "roles" edge.
func HasRoles() predicate.IAMUser {
	return predicate.IAMUser(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, RolesTable, RolesPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRolesWith applies the HasEdge predicate on the "roles" edge with a given conditions (other predicates).
func HasRolesWith(preds ...predicate.IAMRole) predicate.IAMUser {
	return predicate.IAMUser(func(s *sql.Selector) {
		step := newRolesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IAMUser) predicate.IAMUser {
	return predicate.IAMUser(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IAMUser) predicate.IAMUser {
	return predicate.IAMUser(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IAMUser) predicate.IAMUser {
	return predicate.IAMUser(sql.NotPredicates(p))
}
