// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/solikewind/happyeat/dal/model/menu/ent/menuspec"
	"github.com/solikewind/happyeat/dal/model/menu/ent/predicate"
)

// MenuSpecDelete is the builder for deleting a MenuSpec entity.
type MenuSpecDelete struct {
	config
	hooks    []Hook
	mutation *MenuSpecMutation
}

// Where appends a list predicates to the MenuSpecDelete builder.
func (_d *MenuSpecDelete) Where(ps ...predicate.MenuSpec) *MenuSpecDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MenuSpecDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MenuSpecDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MenuSpecDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(menuspec.Table, sqlgraph.NewFieldSpec(menuspec.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MenuSpecDeleteOne is the builder for deleting a single MenuSpec entity.
type MenuSpecDeleteOne struct {
	_d *MenuSpecDelete
}

// Where appends a list predicates to the MenuSpecDelete builder.
func (_d *MenuSpecDeleteOne) Where(ps ...predicate.MenuSpec) *MenuSpecDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MenuSpecDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{menuspec.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MenuSpecDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
