// Code generated by ent, DO NOT EDIT.

package categoryspec

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the categoryspec type in the database.
	Label = "category_spec"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeleteTs holds the string denoting the delete_ts field in the database.
	FieldDeleteTs = "delete_ts"
	// FieldMenuCategoryID holds the string denoting the menu_category_id field in the database.
	FieldMenuCategoryID = "menu_category_id"
	// FieldSpecItemID holds the string denoting the spec_item_id field in the database.
	FieldSpecItemID = "spec_item_id"
	// FieldSpecType holds the string denoting the spec_type field in the database.
	FieldSpecType = "spec_type"
	// FieldSpecValue holds the string denoting the spec_value field in the database.
	FieldSpecValue = "spec_value"
	// FieldPriceDelta holds the string denoting the price_delta field in the database.
	FieldPriceDelta = "price_delta"
	// FieldSort holds the string denoting the sort field in the database.
	FieldSort = "sort"
	// EdgeCategory holds the string denoting the category edge name in mutations.
	EdgeCategory = "category"
	// EdgeSpecItem holds the string denoting the spec_item edge name in mutations.
	EdgeSpecItem = "spec_item"
	// EdgeMenuSpecs holds the string denoting the menu_specs edge name in mutations.
	EdgeMenuSpecs = "menu_specs"
	// Table holds the table name of the categoryspec in the database.
	Table = "category_specs"
	// CategoryTable is the table that holds the category relation/edge.
	CategoryTable = "category_specs"
	// CategoryInverseTable is the table name for the MenuCategory entity.
	// It exists in this package in order to avoid circular dependency with the "menucategory" package.
	CategoryInverseTable = "menu_categories"
	// CategoryColumn is the table column denoting the category relation/edge.
	CategoryColumn = "menu_category_id"
	// SpecItemTable is the table that holds the spec_item relation/edge.
	SpecItemTable = "category_specs"
	// SpecItemInverseTable is the table name for the SpecItem entity.
	// It exists in this package in order to avoid circular dependency with the "specitem" package.
	SpecItemInverseTable = "spec_items"
	// SpecItemColumn is the table column denoting the spec_item relation/edge.
	SpecItemColumn = "spec_item_id"
	// MenuSpecsTable is the table that holds the menu_specs relation/edge.
	MenuSpecsTable = "menu_specs"
	// MenuSpecsInverseTable is the table name for the MenuSpec entity.
	// It exists in this package in order to avoid circular dependency with the "menuspec" package.
	MenuSpecsInverseTable = "menu_specs"
	// MenuSpecsColumn is the table column denoting the menu_specs relation/edge.
	MenuSpecsColumn = "category_spec_id"
)

// Columns holds all SQL columns for categoryspec fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeleteTs,
	FieldMenuCategoryID,
	FieldSpecItemID,
	FieldSpecType,
	FieldSpecValue,
	FieldPriceDelta,
	FieldSort,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/solikewind/happyeat/dal/model/ent/runtime"
var (
	Hooks        [2]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultDeleteTs holds the default value on creation for the "delete_ts" field.
	DefaultDeleteTs int64
	// SpecTypeValidator is a validator for the "spec_type" field. It is called by the builders before save.
	SpecTypeValidator func(string) error
	// SpecValueValidator is a validator for the "spec_value" field. It is called by the builders before save.
	SpecValueValidator func(string) error
	// DefaultPriceDelta holds the default value on creation for the "price_delta" field.
	DefaultPriceDelta int64
	// DefaultSort holds the default value on creation for the "sort" field.
	DefaultSort uint32
)

// OrderOption defines the ordering options for the CategorySpec queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeleteTs orders the results by the delete_ts field.
func ByDeleteTs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeleteTs, opts...).ToFunc()
}

// ByMenuCategoryID orders the results by the menu_category_id field.
func ByMenuCategoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMenuCategoryID, opts...).ToFunc()
}

// BySpecItemID orders the results by the spec_item_id field.
func BySpecItemID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpecItemID, opts...).ToFunc()
}

// BySpecType orders the results by the spec_type field.
func BySpecType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpecType, opts...).ToFunc()
}

// BySpecValue orders the results by the spec_value field.
func BySpecValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpecValue, opts...).ToFunc()
}

// ByPriceDelta orders the results by the price_delta field.
func ByPriceDelta(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriceDelta, opts...).ToFunc()
}

// BySort orders the results by the sort field.
func BySort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSort, opts...).ToFunc()
}

// ByCategoryField orders the results by category field.
func ByCategoryField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCategoryStep(), sql.OrderByField(field, opts...))
	}
}

// BySpecItemField orders the results by spec_item field.
func BySpecItemField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSpecItemStep(), sql.OrderByField(field, opts...))
	}
}

// ByMenuSpecsCount orders the results by menu_specs count.
func ByMenuSpecsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMenuSpecsStep(), opts...)
	}
}

// ByMenuSpecs orders the results by menu_specs terms.
func ByMenuSpecs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMenuSpecsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCategoryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CategoryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CategoryTable, CategoryColumn),
	)
}
func newSpecItemStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SpecItemInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SpecItemTable, SpecItemColumn),
	)
}
func newMenuSpecsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MenuSpecsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MenuSpecsTable, MenuSpecsColumn),
	)
}
