// Code generated by ent, DO NOT EDIT.

package categoryspec

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/solikewind/happyeat/dal/model/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeleteTs applies equality check predicate on the "delete_ts" field. It's identical to DeleteTsEQ.
func DeleteTs(v int64) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldEQ(FieldDeleteTs, v))
}

// SpecType applies equality check predicate on the "spec_type" field. It's identical to SpecTypeEQ.
func SpecType(v string) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldEQ(FieldSpecType, v))
}

// SpecValue applies equality check predicate on the "spec_value" field. It's identical to SpecValueEQ.
func SpecValue(v string) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldEQ(FieldSpecValue, v))
}

// PriceDelta applies equality check predicate on the "price_delta" field. It's identical to PriceDeltaEQ.
func PriceDelta(v float64) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldEQ(FieldPriceDelta, v))
}

// Sort applies equality check predicate on the "sort" field. It's identical to SortEQ.
func Sort(v int) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldEQ(FieldSort, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeleteTsEQ applies the EQ predicate on the "delete_ts" field.
func DeleteTsEQ(v int64) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldEQ(FieldDeleteTs, v))
}

// DeleteTsNEQ applies the NEQ predicate on the "delete_ts" field.
func DeleteTsNEQ(v int64) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldNEQ(FieldDeleteTs, v))
}

// DeleteTsIn applies the In predicate on the "delete_ts" field.
func DeleteTsIn(vs ...int64) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldIn(FieldDeleteTs, vs...))
}

// DeleteTsNotIn applies the NotIn predicate on the "delete_ts" field.
func DeleteTsNotIn(vs ...int64) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldNotIn(FieldDeleteTs, vs...))
}

// DeleteTsGT applies the GT predicate on the "delete_ts" field.
func DeleteTsGT(v int64) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldGT(FieldDeleteTs, v))
}

// DeleteTsGTE applies the GTE predicate on the "delete_ts" field.
func DeleteTsGTE(v int64) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldGTE(FieldDeleteTs, v))
}

// DeleteTsLT applies the LT predicate on the "delete_ts" field.
func DeleteTsLT(v int64) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldLT(FieldDeleteTs, v))
}

// DeleteTsLTE applies the LTE predicate on the "delete_ts" field.
func DeleteTsLTE(v int64) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldLTE(FieldDeleteTs, v))
}

// SpecTypeEQ applies the EQ predicate on the "spec_type" field.
func SpecTypeEQ(v string) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldEQ(FieldSpecType, v))
}

// SpecTypeNEQ applies the NEQ predicate on the "spec_type" field.
func SpecTypeNEQ(v string) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldNEQ(FieldSpecType, v))
}

// SpecTypeIn applies the In predicate on the "spec_type" field.
func SpecTypeIn(vs ...string) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldIn(FieldSpecType, vs...))
}

// SpecTypeNotIn applies the NotIn predicate on the "spec_type" field.
func SpecTypeNotIn(vs ...string) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldNotIn(FieldSpecType, vs...))
}

// SpecTypeGT applies the GT predicate on the "spec_type" field.
func SpecTypeGT(v string) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldGT(FieldSpecType, v))
}

// SpecTypeGTE applies the GTE predicate on the "spec_type" field.
func SpecTypeGTE(v string) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldGTE(FieldSpecType, v))
}

// SpecTypeLT applies the LT predicate on the "spec_type" field.
func SpecTypeLT(v string) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldLT(FieldSpecType, v))
}

// SpecTypeLTE applies the LTE predicate on the "spec_type" field.
func SpecTypeLTE(v string) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldLTE(FieldSpecType, v))
}

// SpecTypeContains applies the Contains predicate on the "spec_type" field.
func SpecTypeContains(v string) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldContains(FieldSpecType, v))
}

// SpecTypeHasPrefix applies the HasPrefix predicate on the "spec_type" field.
func SpecTypeHasPrefix(v string) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldHasPrefix(FieldSpecType, v))
}

// SpecTypeHasSuffix applies the HasSuffix predicate on the "spec_type" field.
func SpecTypeHasSuffix(v string) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldHasSuffix(FieldSpecType, v))
}

// SpecTypeEqualFold applies the EqualFold predicate on the "spec_type" field.
func SpecTypeEqualFold(v string) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldEqualFold(FieldSpecType, v))
}

// SpecTypeContainsFold applies the ContainsFold predicate on the "spec_type" field.
func SpecTypeContainsFold(v string) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldContainsFold(FieldSpecType, v))
}

// SpecValueEQ applies the EQ predicate on the "spec_value" field.
func SpecValueEQ(v string) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldEQ(FieldSpecValue, v))
}

// SpecValueNEQ applies the NEQ predicate on the "spec_value" field.
func SpecValueNEQ(v string) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldNEQ(FieldSpecValue, v))
}

// SpecValueIn applies the In predicate on the "spec_value" field.
func SpecValueIn(vs ...string) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldIn(FieldSpecValue, vs...))
}

// SpecValueNotIn applies the NotIn predicate on the "spec_value" field.
func SpecValueNotIn(vs ...string) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldNotIn(FieldSpecValue, vs...))
}

// SpecValueGT applies the GT predicate on the "spec_value" field.
func SpecValueGT(v string) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldGT(FieldSpecValue, v))
}

// SpecValueGTE applies the GTE predicate on the "spec_value" field.
func SpecValueGTE(v string) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldGTE(FieldSpecValue, v))
}

// SpecValueLT applies the LT predicate on the "spec_value" field.
func SpecValueLT(v string) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldLT(FieldSpecValue, v))
}

// SpecValueLTE applies the LTE predicate on the "spec_value" field.
func SpecValueLTE(v string) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldLTE(FieldSpecValue, v))
}

// SpecValueContains applies the Contains predicate on the "spec_value" field.
func SpecValueContains(v string) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldContains(FieldSpecValue, v))
}

// SpecValueHasPrefix applies the HasPrefix predicate on the "spec_value" field.
func SpecValueHasPrefix(v string) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldHasPrefix(FieldSpecValue, v))
}

// SpecValueHasSuffix applies the HasSuffix predicate on the "spec_value" field.
func SpecValueHasSuffix(v string) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldHasSuffix(FieldSpecValue, v))
}

// SpecValueEqualFold applies the EqualFold predicate on the "spec_value" field.
func SpecValueEqualFold(v string) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldEqualFold(FieldSpecValue, v))
}

// SpecValueContainsFold applies the ContainsFold predicate on the "spec_value" field.
func SpecValueContainsFold(v string) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldContainsFold(FieldSpecValue, v))
}

// PriceDeltaEQ applies the EQ predicate on the "price_delta" field.
func PriceDeltaEQ(v float64) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldEQ(FieldPriceDelta, v))
}

// PriceDeltaNEQ applies the NEQ predicate on the "price_delta" field.
func PriceDeltaNEQ(v float64) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldNEQ(FieldPriceDelta, v))
}

// PriceDeltaIn applies the In predicate on the "price_delta" field.
func PriceDeltaIn(vs ...float64) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldIn(FieldPriceDelta, vs...))
}

// PriceDeltaNotIn applies the NotIn predicate on the "price_delta" field.
func PriceDeltaNotIn(vs ...float64) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldNotIn(FieldPriceDelta, vs...))
}

// PriceDeltaGT applies the GT predicate on the "price_delta" field.
func PriceDeltaGT(v float64) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldGT(FieldPriceDelta, v))
}

// PriceDeltaGTE applies the GTE predicate on the "price_delta" field.
func PriceDeltaGTE(v float64) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldGTE(FieldPriceDelta, v))
}

// PriceDeltaLT applies the LT predicate on the "price_delta" field.
func PriceDeltaLT(v float64) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldLT(FieldPriceDelta, v))
}

// PriceDeltaLTE applies the LTE predicate on the "price_delta" field.
func PriceDeltaLTE(v float64) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldLTE(FieldPriceDelta, v))
}

// SortEQ applies the EQ predicate on the "sort" field.
func SortEQ(v int) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldEQ(FieldSort, v))
}

// SortNEQ applies the NEQ predicate on the "sort" field.
func SortNEQ(v int) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldNEQ(FieldSort, v))
}

// SortIn applies the In predicate on the "sort" field.
func SortIn(vs ...int) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldIn(FieldSort, vs...))
}

// SortNotIn applies the NotIn predicate on the "sort" field.
func SortNotIn(vs ...int) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldNotIn(FieldSort, vs...))
}

// SortGT applies the GT predicate on the "sort" field.
func SortGT(v int) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldGT(FieldSort, v))
}

// SortGTE applies the GTE predicate on the "sort" field.
func SortGTE(v int) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldGTE(FieldSort, v))
}

// SortLT applies the LT predicate on the "sort" field.
func SortLT(v int) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldLT(FieldSort, v))
}

// SortLTE applies the LTE predicate on the "sort" field.
func SortLTE(v int) predicate.CategorySpec {
	return predicate.CategorySpec(sql.FieldLTE(FieldSort, v))
}

// HasCategory applies the HasEdge predicate on the "category" edge.
func HasCategory() predicate.CategorySpec {
	return predicate.CategorySpec(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CategoryTable, CategoryColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCategoryWith applies the HasEdge predicate on the "category" edge with a given conditions (other predicates).
func HasCategoryWith(preds ...predicate.MenuCategory) predicate.CategorySpec {
	return predicate.CategorySpec(func(s *sql.Selector) {
		step := newCategoryStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMenuSpecs applies the HasEdge predicate on the "menu_specs" edge.
func HasMenuSpecs() predicate.CategorySpec {
	return predicate.CategorySpec(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MenuSpecsTable, MenuSpecsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMenuSpecsWith applies the HasEdge predicate on the "menu_specs" edge with a given conditions (other predicates).
func HasMenuSpecsWith(preds ...predicate.MenuSpec) predicate.CategorySpec {
	return predicate.CategorySpec(func(s *sql.Selector) {
		step := newMenuSpecsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CategorySpec) predicate.CategorySpec {
	return predicate.CategorySpec(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CategorySpec) predicate.CategorySpec {
	return predicate.CategorySpec(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CategorySpec) predicate.CategorySpec {
	return predicate.CategorySpec(sql.NotPredicates(p))
}
