// Code generated by ent, DO NOT EDIT.

package settlement

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/solikewind/happyeat/common/consts/enum"
	"github.com/solikewind/happyeat/dal/model/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.Settlement {
	return predicate.Settlement(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.Settlement {
	return predicate.Settlement(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.Settlement {
	return predicate.Settlement(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.Settlement {
	return predicate.Settlement(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.Settlement {
	return predicate.Settlement(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.Settlement {
	return predicate.Settlement(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.Settlement {
	return predicate.Settlement(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeleteTs applies equality check predicate on the "delete_ts" field. It's identical to DeleteTsEQ.
func DeleteTs(v int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldDeleteTs, v))
}

// CustomerName applies equality check predicate on the "customer_name" field. It's identical to CustomerNameEQ.
func CustomerName(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldCustomerName, v))
}

// TotalAmount applies equality check predicate on the "total_amount" field. It's identical to TotalAmountEQ.
func TotalAmount(v int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldTotalAmount, v))
}

// ActualAmount applies equality check predicate on the "actual_amount" field. It's identical to ActualAmountEQ.
func ActualAmount(v int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldActualAmount, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldRemark, v))
}

// SettledAt applies equality check predicate on the "settled_at" field. It's identical to SettledAtEQ.
func SettledAt(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldSettledAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeleteTsEQ applies the EQ predicate on the "delete_ts" field.
func DeleteTsEQ(v int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldDeleteTs, v))
}

// DeleteTsNEQ applies the NEQ predicate on the "delete_ts" field.
func DeleteTsNEQ(v int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldNEQ(FieldDeleteTs, v))
}

// DeleteTsIn applies the In predicate on the "delete_ts" field.
func DeleteTsIn(vs ...int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldIn(FieldDeleteTs, vs...))
}

// DeleteTsNotIn applies the NotIn predicate on the "delete_ts" field.
func DeleteTsNotIn(vs ...int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldNotIn(FieldDeleteTs, vs...))
}

// DeleteTsGT applies the GT predicate on the "delete_ts" field.
func DeleteTsGT(v int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldGT(FieldDeleteTs, v))
}

// DeleteTsGTE applies the GTE predicate on the "delete_ts" field.
func DeleteTsGTE(v int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldGTE(FieldDeleteTs, v))
}

// DeleteTsLT applies the LT predicate on the "delete_ts" field.
func DeleteTsLT(v int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldLT(FieldDeleteTs, v))
}

// DeleteTsLTE applies the LTE predicate on the "delete_ts" field.
func DeleteTsLTE(v int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldLTE(FieldDeleteTs, v))
}

// CustomerNameEQ applies the EQ predicate on the "customer_name" field.
func CustomerNameEQ(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldCustomerName, v))
}

// CustomerNameNEQ applies the NEQ predicate on the "customer_name" field.
func CustomerNameNEQ(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldNEQ(FieldCustomerName, v))
}

// CustomerNameIn applies the In predicate on the "customer_name" field.
func CustomerNameIn(vs ...string) predicate.Settlement {
	return predicate.Settlement(sql.FieldIn(FieldCustomerName, vs...))
}

// CustomerNameNotIn applies the NotIn predicate on the "customer_name" field.
func CustomerNameNotIn(vs ...string) predicate.Settlement {
	return predicate.Settlement(sql.FieldNotIn(FieldCustomerName, vs...))
}

// CustomerNameGT applies the GT predicate on the "customer_name" field.
func CustomerNameGT(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldGT(FieldCustomerName, v))
}

// CustomerNameGTE applies the GTE predicate on the "customer_name" field.
func CustomerNameGTE(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldGTE(FieldCustomerName, v))
}

// CustomerNameLT applies the LT predicate on the "customer_name" field.
func CustomerNameLT(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldLT(FieldCustomerName, v))
}

// CustomerNameLTE applies the LTE predicate on the "customer_name" field.
func CustomerNameLTE(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldLTE(FieldCustomerName, v))
}

// CustomerNameContains applies the Contains predicate on the "customer_name" field.
func CustomerNameContains(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldContains(FieldCustomerName, v))
}

// CustomerNameHasPrefix applies the HasPrefix predicate on the "customer_name" field.
func CustomerNameHasPrefix(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldHasPrefix(FieldCustomerName, v))
}

// CustomerNameHasSuffix applies the HasSuffix predicate on the "customer_name" field.
func CustomerNameHasSuffix(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldHasSuffix(FieldCustomerName, v))
}

// CustomerNameEqualFold applies the EqualFold predicate on the "customer_name" field.
func CustomerNameEqualFold(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldEqualFold(FieldCustomerName, v))
}

// CustomerNameContainsFold applies the ContainsFold predicate on the "customer_name" field.
func CustomerNameContainsFold(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldContainsFold(FieldCustomerName, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v enum.SettlementStatus) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v enum.SettlementStatus) predicate.Settlement {
	return predicate.Settlement(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...enum.SettlementStatus) predicate.Settlement {
	return predicate.Settlement(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...enum.SettlementStatus) predicate.Settlement {
	return predicate.Settlement(sql.FieldNotIn(FieldStatus, vs...))
}

// TotalAmountEQ applies the EQ predicate on the "total_amount" field.
func TotalAmountEQ(v int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldTotalAmount, v))
}

// TotalAmountNEQ applies the NEQ predicate on the "total_amount" field.
func TotalAmountNEQ(v int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldNEQ(FieldTotalAmount, v))
}

// TotalAmountIn applies the In predicate on the "total_amount" field.
func TotalAmountIn(vs ...int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldIn(FieldTotalAmount, vs...))
}

// TotalAmountNotIn applies the NotIn predicate on the "total_amount" field.
func TotalAmountNotIn(vs ...int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldNotIn(FieldTotalAmount, vs...))
}

// TotalAmountGT applies the GT predicate on the "total_amount" field.
func TotalAmountGT(v int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldGT(FieldTotalAmount, v))
}

// TotalAmountGTE applies the GTE predicate on the "total_amount" field.
func TotalAmountGTE(v int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldGTE(FieldTotalAmount, v))
}

// TotalAmountLT applies the LT predicate on the "total_amount" field.
func TotalAmountLT(v int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldLT(FieldTotalAmount, v))
}

// TotalAmountLTE applies the LTE predicate on the "total_amount" field.
func TotalAmountLTE(v int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldLTE(FieldTotalAmount, v))
}

// ActualAmountEQ applies the EQ predicate on the "actual_amount" field.
func ActualAmountEQ(v int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldActualAmount, v))
}

// ActualAmountNEQ applies the NEQ predicate on the "actual_amount" field.
func ActualAmountNEQ(v int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldNEQ(FieldActualAmount, v))
}

// ActualAmountIn applies the In predicate on the "actual_amount" field.
func ActualAmountIn(vs ...int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldIn(FieldActualAmount, vs...))
}

// ActualAmountNotIn applies the NotIn predicate on the "actual_amount" field.
func ActualAmountNotIn(vs ...int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldNotIn(FieldActualAmount, vs...))
}

// ActualAmountGT applies the GT predicate on the "actual_amount" field.
func ActualAmountGT(v int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldGT(FieldActualAmount, v))
}

// ActualAmountGTE applies the GTE predicate on the "actual_amount" field.
func ActualAmountGTE(v int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldGTE(FieldActualAmount, v))
}

// ActualAmountLT applies the LT predicate on the "actual_amount" field.
func ActualAmountLT(v int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldLT(FieldActualAmount, v))
}

// ActualAmountLTE applies the LTE predicate on the "actual_amount" field.
func ActualAmountLTE(v int64) predicate.Settlement {
	return predicate.Settlement(sql.FieldLTE(FieldActualAmount, v))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.Settlement {
	return predicate.Settlement(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.Settlement {
	return predicate.Settlement(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.Settlement {
	return predicate.Settlement(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.Settlement {
	return predicate.Settlement(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.Settlement {
	return predicate.Settlement(sql.FieldContainsFold(FieldRemark, v))
}

// SettledAtEQ applies the EQ predicate on the "settled_at" field.
func SettledAtEQ(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldEQ(FieldSettledAt, v))
}

// SettledAtNEQ applies the NEQ predicate on the "settled_at" field.
func SettledAtNEQ(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldNEQ(FieldSettledAt, v))
}

// SettledAtIn applies the In predicate on the "settled_at" field.
func SettledAtIn(vs ...time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldIn(FieldSettledAt, vs...))
}

// SettledAtNotIn applies the NotIn predicate on the "settled_at" field.
func SettledAtNotIn(vs ...time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldNotIn(FieldSettledAt, vs...))
}

// SettledAtGT applies the GT predicate on the "settled_at" field.
func SettledAtGT(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldGT(FieldSettledAt, v))
}

// SettledAtGTE applies the GTE predicate on the "settled_at" field.
func SettledAtGTE(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldGTE(FieldSettledAt, v))
}

// SettledAtLT applies the LT predicate on the "settled_at" field.
func SettledAtLT(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldLT(FieldSettledAt, v))
}

// SettledAtLTE applies the LTE predicate on the "settled_at" field.
func SettledAtLTE(v time.Time) predicate.Settlement {
	return predicate.Settlement(sql.FieldLTE(FieldSettledAt, v))
}

// SettledAtIsNil applies the IsNil predicate on the "settled_at" field.
func SettledAtIsNil() predicate.Settlement {
	return predicate.Settlement(sql.FieldIsNull(FieldSettledAt))
}

// SettledAtNotNil applies the NotNil predicate on the "settled_at" field.
func SettledAtNotNil() predicate.Settlement {
	return predicate.Settlement(sql.FieldNotNull(FieldSettledAt))
}

// HasOrders applies the HasEdge predicate on the "orders" edge.
func HasOrders() predicate.Settlement {
	return predicate.Settlement(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, OrdersTable, OrdersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrdersWith applies the HasEdge predicate on the "orders" edge with a given conditions (other predicates).
func HasOrdersWith(preds ...predicate.Order) predicate.Settlement {
	return predicate.Settlement(func(s *sql.Selector) {
		step := newOrdersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Settlement) predicate.Settlement {
	return predicate.Settlement(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Settlement) predicate.Settlement {
	return predicate.Settlement(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Settlement) predicate.Settlement {
	return predicate.Settlement(sql.NotPredicates(p))
}
